vaadin/platform

versions.json
* Mention vaadin-overlay in the release note
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1066)
=> Mention vaadin-overlay in the release note (#1065)

.travis.yml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1071)
=> Update Flow version to 2.2.0.alpha8

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1072)
=> Update CDI version to 11.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1073)
=> Updated Spring to 12.2.0.alpha1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1069)
=> Bump Vaadin Router npm package version

.travis.yml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1074)
=> Update Flow version to 3.0.0.alpha13

scripts/generator/generate.js, scripts/generator/templates/template-vaadin-package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1075)
=> Remove bower stuff from master branch

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1078)
=> Update vaadin-list-box-flow to 2.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1081)
=> Update vaadin-list-box-flow to 2.1.1 (#1078)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1082)
=> Drop safari 11 support

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1084)
=> Test against Safari 12

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1085)
=> Update release note about safari 12 support

scripts/generator/templates/template-release-notes.md
This probably a temporary version. will need to revisit the whole content before beta/rc releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1086)
=> Mention pnpm update in 14.2 release note

versions.json
Update Flow version to 3.0.0.alpha14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1087)
=> Update Flow version to 3.0.0.alpha14

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1090)
=> Update vaadin-custom-field version for 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1088)
=> Update vaadin-custom-field version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1089)
=> Update vaadin-custom-field version for 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1094)
=> Bump Flow version to 2.1.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1097)
=> Update Flow version to 2.2.0.alpha9

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1098)
=> Update to test with Safari 13 instead of 12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1103)
=> Updated vaadin-spring to version 13.0.0.alpha4

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
This will let us find the client side error easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1099)
=> Check the console log for the component testing UI

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1106)
=> Update Flow to version 2.2.0.alpha10

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1107)
=> Replace the Known issues section with link in maintain release note

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
* Check the console log for the component testing UI
This will let us find the client side error easier.
* Execulde the ironListStyles.css from the error log
this is a bug in flow which is mentioned in ticket https://github.com/vaadin/flow/issues/6948
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1104)
=> Check the console log for the component testing UI (#1099)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1110)
=> V15 components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1117)
=> Update Flow version to 2.2.0.alpha12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1119)
=> Update Spring version to 12.2.0.alpha2

versions.json
Fixes #1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1124)
=> Bump shadycss and polymer behaviors

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1125)
=> Update Flow version to 3.0.0.alpha17

versions.json
See the [release note](https://github.com/vaadin/spring/releases/tag/13.0.0.alpha5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1126)
=> Updated vaadin-spring to version 13.0.0.alpha5

vaadin-core/pom.xml, vaadin-core/src/test/java/VersionsFileTest.java
Part of vaadin/flow#7451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1127)
=> Include versions.json to vaadin-core

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1131)
=> V15 beta1 components

vaadin-core/pom.xml, vaadin-core/src/test/java/VersionsFileTest.java
Part of vaadin/flow#7451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1133)
=> CP: Include versions.json to vaadin-core (#1127)

versions.json
Use Spring 13.0.0.beta1 and CDI 12.0.0.beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1137)
=> Update Spring and CDI versions

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1138)
=> Updated the text to full release notes

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
Fixes #1100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1136)
=> Remove the workaround for ironListStyles.css (#1135)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1141)
=> Bump to Flow 2.1.5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1142)
=> Bump Flow and Spring addon versions

scripts/updateVersions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1144)
=> Add script for version update

scripts/updateVersions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1146)
=> Add script for version update (#1144)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1149)
=> Update ordered layout to new minor targeting 14.2

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1151)
=> Add Edge-18 into test

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1152)
=> Add EdgeHTML(edge-18) to test

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1153)
=> Add edge-18 to test (10.0)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1155)
=> Update flow and mpr versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1156)
=> Update ordered layout to latest alpha

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1159)
=> Bump grid to 5.0.0.beta2 in master

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1161)
=> Bump grid to 4.1.2 in 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1160)
=> Bump grid to 4.1.2 in 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1164)
=> Update Flow version to 3.0.0.beta3

scripts/updateVersions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1165)
=> sort the output when making auto PR

scripts/updateVersions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1166)
=> sort the output when making auto PR (#1165)

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
Related to vaadin/flow#7623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1176)
=> Add known issue for default link behaviour in Flow 3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1179)
=> Update flow version to 2.2.0.alpha14

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1181)
=> Update versions for 14.1

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1182)
=> Added IE to release note template

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1185)
=> V15 stable components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1186)
=> Bump Vaadin Router version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1187)
=> Bump Spring CDI and MPR versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1188)
=> Update app-layout to 2.0.5

versions.json
Cherrypick this to 14.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1191)
=> Update to mpr 2.0.2

platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1192)
=> Update to Vaadin 16.0-SNAPSHOT

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1190)
=> Experiment with Flow 3.1-SNAPSHOT

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1193)
=> Update MPR version to 2.0.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1198)
=> Update vaadin-spring to 12.1.3

scripts/generator/templates/template-release-notes-maintenance.md
Moved "support" to lower section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1200)
=> Update to maintenance release notes template

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1201)
=> Update vaadin-overlay v16

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1202)
=> Update vaadin-overlay v15

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1203)
=> Update vaadin-overlay v14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1204)
=> Update vaadin-overlay v14.1

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1205)
=> preventing long logs.

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1209)
=> Bump icons-flow to 2.0.3 in 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1208)
=> Bump icons-flow to 2.0.3 in 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1215)
=> Update vaadin-radio-button v14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1213)
=> Update vaadin-radio-button v16

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1214)
=> Update vaadin-radio-button v15

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1218)
=> Update MPR version to 2.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1217)
=> Update MPR version to 3.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1219)
=> update MPR to 2.0.3

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1220)
=> v16 release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1225)
=> Update flow version to use snapshot

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1226)
=> Update flow and spring addon versions

vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1228)
=> Update enforcer plugin version and enforce no-snapshot rule

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1229)
=> Update vaadin-parent to 2.0.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1227)
=> Bump dialog versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1235)
=> Bump confirm dialog

scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-testbench/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1237)
=> Add vaadin-date-time-picker into versions.json

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1244)
=> Bump vaadin-ordered-layout-flow 2.1.0.alpha5 in 14.2

versions.json
vaadin-text-field-flow 3.0.1
vaadin-checkbox-flow 3.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1245)
=> Bump versions (master)

versions.json
vaadin-text-field-flow 3.0.1
vaadin-checkbox-flow 3.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1246)
=> Bump versions (15.0)

versions.json
vaadin-text-field-flow 2.1.1
vaadin-checkbox-flow 2.0.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1247)
=> Bump versions (14.1)

versions.json
vaadin-time-picker-flow 2.1.0.alpha1
vaadin-text-field-flow 2.1.1
vaadin-checkbox-flow 2.0.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1248)
=> Bump versions (14.2)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1254)
=> Downgrade Flow to 2.1.6

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1256)
=> Update flow 2.1.7 and spring 12.1.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1257)
=> Update vaadin-combo-box-flow to version with high priority fix

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1265)
=> Update 15.0 maintenance-release-note template on known issue

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1267)
=> Update vaadin-spring to 13.0.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1274)
=> Update Spring version to 12.2.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1277)
=> Update flow to 3.1.0.alpha1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1278)
=> Update Spring to 13.0.2

platform-servlet-containers-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1279)
=> rename the plugin repo id to Vaadin Directory

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1280)
=> Add known features to V16 prerelease-note template

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1281)
=> Update flow-cdi to 11.2.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1282)
=> Update components for 14.2 beta

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, vaadin-testbench/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1285)
=> V16 components

versions.json
Also update list-box js version to latest alpha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1286)
=> Update js and java versions for ordered layout

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1283)
=> Update V14.2 prerelease release note

platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1295)
=> Update platform to Vaadin 17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1297)
=> Update vaadin-menu-bar version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1298)
=> Update vaadin-date-picker version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1307)
=> Update Crud to 2.1.2 (V14.2)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1308)
=> Update Crud to 2.1.2 (V14.1)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1305)
=> Update Crud to 3.1.0.alpha2 (V16)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1306)
=> Update Crud to 3.0.1 (V15)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1304)
=> Update Crud to 3.1.0.alpha2 (V17)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1310)
=> Update menu-bar version for 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1309)
=> Update menu-bar version for 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1312)
=> Update vaadin-menu-bar to latest

pom.xml, vaadin-spring-boot-starter/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1313)
=> Enable vaadin-prerelease for snapshot

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1319)
=> Update vaadin-router to 1.7.2

pom.xml, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1317)
=> Update snapshot usages-14.1

pom.xml, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1316)
=> Update snapshot usages-14.2

pom.xml, vaadin-spring-boot-starter/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1314)
=> Snasphot change 15.0

pom.xml, vaadin-spring-boot-starter/pom.xml
* Enable vaadin-prerelease for snapshot
* add snapshot setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1315)
=> Enable vaadin-prerelease for snapshot (#1313)

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1322)
=> Prepare release note for V14.2 GA

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1323)
=> Add component features.

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1327)
=> Update TB version

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1326)
=> Add components feature added to V14.2

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1334)
=> Update maintenance release note template.

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1336)
=> Updated release notes based on pre-release

scripts/generator/templates/template-release-notes.md
Added "globally" to text "No need to have Node installed for CI"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1343)
=> Updated notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1345)
=> 14.2 components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1347)
=> Update flow-cdi to 11.2.0

.travis.yml, platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/package-lock.json, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1353)
=> Update Project to 14.3-SNAPSHOT an prepare release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1358)
=> Update component versions for v16

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1359)
=> Bump vaadin-overlay version [v16]

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1362)
=> Bump vaadin-overlay version [v15]

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1361)
=> Bump vaadin-overlay version [v14.2]

.travis.yml, scripts/validateVersions.js, scripts/verifyNpmDependencies.sh
This should 
- be cherry-picked to all active branches
- be included at the beginning of CI builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1364)
=> add validation script for versions and fix the one for checking duplicates

.travis.yml, scripts/validateVersions.js, scripts/verifyNpmDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1370)
=> 1364 cherry pick 16.0

scripts/generator/templates/template-release-notes-prerelease.md
Added main feature from flow update
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1365)
=> Update prerelease note template for 14.3

.travis.yml, scripts/validateVersions.js, scripts/verifyNpmDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1371)
=> 1364 cherry pick 15.0

.travis.yml, scripts/validateVersions.js, scripts/verifyNpmDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1369)
=> 1364 cherry pick 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1373)
=> Updated Flow version of Vaadin 17 to 3.2.0.alpha4

scripts/generator/templates/template-vaadin-spring-bom.xml, versions.json
Fixes #1363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1380)
=> Add java LC to versions.js and bom

.travis.yml, scripts/validateVersions.js, scripts/verifyNpmDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1372)
=> 1364 cherry pick 14.3

.github/workflows/greetings.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1339)
=> Add auto greetings

scripts/generator/templates/template-vaadin-spring-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1388)
=> cp: Add java LC to versions.js and bom (#1380)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1390)
=> Update components versions for V17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1392)
=> Update charts and select for V17

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1394)
=> Bump component versions for platform branch: 14.3

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1395)
=> Update release note template for V17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1397)
=> Bump iron list versions for 14.3

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1398)
=> Remove outdated limitation

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1404)
=> Bump component versions for platform branch: master

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1406)
=> Updated CDI to 12.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1407)
=> Bump component versions for platform branch: 14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1408)
=> Bump iron-list versions for 17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1417)
=> Update CDI for 14.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1418)
=> Bump dialog for V14.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1419)
=> Bump dialog for V17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1420)
=> Bump dialog for V16

.github/ISSUE_TEMPLATE/acceptance-criteria.md
Created a proposal for the template for the Acceptance Criteria checklist, where there is a user story followed by a checklist.
The checklist contains the case-specific criteria, and then also the generic ones (for APIs, performance, UX/DX tests and design).
The part under construction is meant for replacing the User Value document in the second iteration of AC changes.
The AC template is designated by default title AC, and a label `acceptance criteria`.
The template is to be used in epics or in single issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1415)
=> Created the Acceptance Criteria (AC) template

versions.json
Part of #639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1423)
=> Update Flow and Spring to 14.3 feature releases (#639)

.github/ISSUE_TEMPLATE/bug_report.md
https://github.com/vaadin/platform/pull/1415#issuecomment-652614880
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1424)
=> Add Bug report template

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1428)
=> Update vaadin-parent to 2.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1429)
=> Update testbench for v17

.github/workflows/greetings.yml
Greetings contain some parts that probably shouldn't be there.
Examples: https://github.com/vaadin/platform/issues/1431#issuecomment-654836099 and https://github.com/vaadin/platform/pull/1415#pullrequestreview-439749343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1432)
=> Cleanup greetings comment messages

BUILD.md, pom.xml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1430)
=> Use standard property to disable ITs

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1437)
=> Update components for v16

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1438)
=> Bring back profile to disable IT's module on releasing

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1439)
=> Update MPR version to 3.0.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1440)
=> Update components v16

.travis.yml, platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1435)
=> Create new branch for 14.4-snapshot

versions.json
Update the router version fixes a couple of Router Link issues. e.g. https://github.com/vaadin/flow/issues/8575, https://github.com/vaadin/flow/issues/8689.
The master branch has already been using 1.7.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1441)
=> update router version to 1.7.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1443)
=> Update charts version for v17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1445)
=> Update MPR version to 2.0.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1444)
=> Bump confirm dialog for 14.3

.github/ISSUE_TEMPLATE/acceptance-criteria.md
Changed `known issues` to `limitations`.
Explained what can be linked to the list of generic acceptance criteria.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1447)
=> Acceptance criteria feedback

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1448)
=> Update confirm dialog for v16

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1456)
=> Bump component versions for platform branch: 16.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1460)
=> Bump components versions for 16.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1459)
=> Bump components versions for 14.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1464)
=> Update Spring add-on version to 12.3.1

versions.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1471)
=> V17 beta components

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1472)
=> Update V17 release note for prerelease

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1473)
=> Rephrase for new feature in Vaadin 17

scripts/generator/templates/template-release-notes-prerelease.md
Fixes #1474 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1475)
=> Mention the dataprovider update and breaking changes

versions.json
Update MPR to 2.0.5 to receive fix for current instance fallback resolvers
registration making legacy request handling stabler.
Also adds checks for easier problem debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1478)
=> Update MPR to v2.0.5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1490)
=> Update for flow 4.0.0.rc1 compatibility

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1492)
=> Bump flow components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1496)
=> Bump component versions for v17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1497)
=> Update MPR version to 4.0.0

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1498)
=> Use uppercase for Vaadin

scripts/generator/templates/template-release-notes.md
- Removed the known issue section, as it has been fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1502)
=> Update Vaadin 17 final release note.

versions.json
there will be another PR to update the release note and so on
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1503)
=> keep 14.4 being updated 

platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1499)
=> Prepare vaadin 18.0-snapshot

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1505)
=> Use version tag for flow components instead of hardcoded number

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1504)
=> Update release note template for V14.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1508)
=> Bump component versions for platform branch: 17.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1507)
=> Bump first batch of components for 14.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1513)
=> vaadin-iron-list-flow version should match platform

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1516)
=> Bump remaining component versions for 14.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1519)
=> Bump component versions for platform branch: 14.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1520)
=> Bump version of grid for V17

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1528)
=> Update component versions for V14.3

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1529)
=> Correct the platform version used in maintenance template

.github/ISSUE_TEMPLATE/acceptance-criteria.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1531)
=> Fix typos in acceptance criteria template

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1534)
=> Update flow to 4.0.2

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1538)
=> Mention the Vcom link for BFP

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1539)
=> Mention Vcom link for BFP

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1536)
=> mention the Vcom link for BFP fix

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1563)
=> Update components for 14.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1564)
=> Update Spring add-on to 14.0.3

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1565)
=> Update release note template for OSGi support

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1566)
=> Update Spring add-on to 12.3.2

.travis.yml, platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1568)
=> Prepare branch for 14.5-SNAPSHOT

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1582)
=> Update component version for platform 17.0.7

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1588)
=> Update component version for 14.4.1

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1590)
=> Fill the new feature for V18

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1595)
=> Update mpr to 4.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1594)
=> Update MPR to 2.0.6

scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/test/creatorTest.js
- remove separate versions mentioned in the release note
- update ticket report section
- add statement about the version schema
- attach component monorepo release note to platform
fixes vaadin/vaadin-flow-components#114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1589)
=> Update release note

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1605)
=> Update components for 14.4.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1606)
=> Update pro components for 14.4.2

scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes.md, scripts/generator/test/creatorTest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1602)
=> Attach component monorepo release note to platform (17.0)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1608)
=> Update component version for 17.0.8

scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/test/creatorTest.js
* Update release note
- remove separate versions mentioned in the release note
- update ticket report section
- add statement about the version schema
Co-authored-by: Manuel Carrasco Moñino <manolo@vaadin.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1604)
=> Update release note (#1589)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1613)
=> Update flow 4.0.5 for V17

scripts/generateBoms.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1630)
=> re-factor: refactor bom generator 

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1628)
=> Update prerelease/final releasenotes

scripts/generator/templates/template-release-notes-prerelease.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1639)
=> Correct symbol use in release note

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1642)
=> Fix hard coded version used in version.json

scripts/generator/templates/template-vaadin-bom.xml, versions.json
related to #1669 , osgi test will be added later.
=> Add flow-osgi module back to platform

scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes.md, scripts/generator/test/creatorTest.js
=> Update release note template for 14.4

scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-testbench/pom.xml, versions.json
Cherry-pick of #1577 to `14.5` branch, updated to also include the webjar.
=> Add avatar to platform for V14.5

scripts/generator/templates/template-release-notes-prerelease.md
=> Update release note template for prerelease

vaadin-platform-test/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Entity.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Log.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
At the same time a unit test has been added checking that there are no new components in the classpath without smoke tests
=> test: add missing components to smoke tests.

vaadin-platform-test/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Entity.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Log.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
* test: add class for checking that all components are used in smoke tests
* chore: upgrade jetty version
* test: add missing components in smoke tests
* test: check against all components/tb-elements in classpath
=> test: add missing components to smoke tests. (#1810) (18.0)

pom.xml, vaadin-core/pom.xml, vaadin-core/src/main/feature/feature.xml, vaadin/pom.xml, vaadin/src/main/feature/feature.xml
=> feat: add generate features classifier for vaadin and vaadin-core

scripts/checkForNonPinnedDependencies.sh, scripts/verifyBowerDependencies.sh, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Entity.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/Log.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
* test: add class for checking that all components are used in smoke tests
* chore: upgrade jetty version
* test: add missing components in smoke tests
* test: check against all components/tb-elements in classpath
=> test: add missing components to smoke tests. (#1810) (14.5)

scripts/generateBoms.sh, scripts/generator/generate.js, scripts/generator/src/creator.js, scripts/generator/src/writer.js, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml
=> fix: remove flow-maven-plugin from vaadin-spring-bom

vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.global.css, vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.ts, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/cssloader/CssLoaderIT.java
test for https://github.com/vaadin/flow/issues/10080
=> test: add test for global css loader

scripts/generator/templates/template-vaadin-spring-bom.xml
Related to https://github.com/vaadin/flow/issues/10182
=> chore: fix theme integration versions

versions.json
There is now first alpha of web components released from the monorepo.
=> feat: use unified web components versions

vaadin-platform-hybrid-test/frontend/utils/a-notification.ts, vaadin-platform-hybrid-test/frontend/utils/css-utils.ts, vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.ts, vaadin-platform-hybrid-test/frontend/views/main/main-view.ts, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-hybrid-test/src/main/java/com/vaadin/platform/fusion/test/Application.java
This fixes problem described for starters in https://github.com/vaadin/start/issues/1123
=> chore: remove unused dependency

.github/ISSUE_TEMPLATE/acceptance-criteria.md
- Move the description section first, so that it is easy to see what this AC/feature is all about
- Add a header for the use cases as it didn't have one.
=> Update AC issue template [skip ci]

versions.json
Update the multiplatform runtime version
to 2.1.1 with fixed route resolving.
=> Update multiplatform-runtime to 2.1.1

.gitignore, platform-servlet-containers-tests/bnd-tools-test/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-platform-hybrid-test/pom-dev-mode.xml, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
=> chore: update platform to 21.0-snapshot

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
=> chore: udpate platform 14.7-SNAPSHOT

versions.json
=> chore: keep versions in 14.7 being synced.

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, versions.json
=> chore: update webcomponent version in master

versions.json
=> keep versions in 14.7 updated

versions.json
=> chore: update CE to 3.1.0

versions.json
=> keep the versions in master branch being updated.

scripts/generator/templates/template-release-notes.md
=> chore: Add maven and gradle version to template

versions.json
=> chore: update vaadin-osgi to 7.0.0

scripts/updateVersions.py
=> chore:fix version update for osgi [skip ci]

scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml
=> chore: Remove skipTests profile from gradle module [skip ci]

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, versions.json
=> chore: remove legacy gradle plugin version

versions.json
=> chore: keep versions being updated on master

versions.json
This reverts commit 742e8bd3e76c8aa9512f3d1be9e785572d7a6f9f.
alpha6 has a few more breaking changes. so we decided to skip this for now. to release a new alpha for DS DX
=> Revert "chore: update versions.json in master with latest WC (#2180)"

versions.json
=> chore: bump MPR for v20

pom.xml, vaadin-core-jandex/pom.xml, vaadin-core-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java, vaadin-jandex/pom.xml, vaadin-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java
Generate jandex index package for
vaadin and vaadin-core.
Closes vaadin/flow#9862
=> feat: Add generation of jandex index

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts
Fix the generic type of an item in the virtual-list test
=> chore: fix virtual list test typings

versions.json
=> chore: update CE to 3.2.0.alpha3

scripts/generator/templates/template-vaadin-spring-bom.xml
=> Chore: add jandex module to the bom template

README.md
Updating the README with start.vaadin.com info
Removed the **Starters** section and updated the **Getting started** with start.vaadin.com info.
=> Updating the README with latest info [skip ci]

scripts/generator/templates/template-vaadin-bom.xml
keep the version in sync with flow https://github.com/vaadin/flow/pull/11457
=> chore: Update slf4j to 1.7.32

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
=> Chore: update ci-sauce plugin version

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
=> test: forward grid.browsers parameter

versions.json
=> chore: update CE to 3.2.0.beta1

versions.json
=> Update Spring add-on to 18.0.0.beta1

versions.json
=> chore: update wc to 22.0.0-alpha1

versions.json
=> Update MPR version to 2.2.3

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
=> test: testing safari-14

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
=> test: test latest safari

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
Changed the templates for the release notes to have correct links to our repositories.
=> Updates to the release notes templates [skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, versions.json
=> feat: add vaadin renderer module

versions.json
=> chore: update CE to 3.2.0.rc1

versions.json
=> Update Vaadin 20 to use MPR 5.0.4

versions.json
=> Update Vaadin 21 to use MPR 5.0.4

versions.json
=> Update Vaadin 14.7 to MPR 2.2.4

versions.json
=> Update Vaadin 22 to use MPR 5.0.4

versions.json
=> chore: update CE to 3.2.0

versions.json
Related to https://github.com/vaadin/web-components/issues/1992
- Version bump
=> chore: add new npm packages to versions.json

scripts/generator/generate.js, scripts/generator/src/creator.js, scripts/generator/templates/template-modules-release-notes.md
=> chore: fix bom generation [skip ci]

scripts/generator/templates/template-release-notes.md
=> chore: add new archetype to template [skip ci]

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
=> chore: update project to 14.8

versions.json
This is a new JS package used by many components in Vaadin 22, similar to `@vaadin/field-base` added previously.
=> chore: add component-base JS package

scripts/generator/templates/template-release-notes.md
=> chore: update release note template for 14.7+ [skip ci]

scripts/generator/templates/template-release-notes.md
=> chore: fix links in release note [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md
=> chore: update maintenance releasenote [skip ci]

versions.json
=> Collaboration engine 4.0.0.alpha1

versions.json
=> Bump Collaboration engine to 3.2.2 (V21)

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, versions.json
=> chore: add new flow components to test

scripts/generator/templates/template-release-notes.md
=> chore: mention Java 17 LTS in the release note. [skip ci]

vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java, vaadin-core/src/test/java/VersionsFileTest.java, vaadin-platform-gradle-test/src/test/java/com/vaadin/platform/gradle/test/AbstractPlatformTest.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeDeviceTest.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeOfflineIT.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ComponentsIT.java, vaadin-platform-servlet-containers-tests/bnd-tools-test/src/test/java/com/vaadin/platform/wait/WaitHttpIT.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/CustomServletDeployer.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/osgi/Activator.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/AbstractPlatformTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java
=> chore:update copyright header [skip ci]

platform-servlet-containers-tests/felix-jetty/src/test/java/com/vaadin/platform/wait/WaitHttpIT.java, vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java, vaadin-core/src/test/java/VersionsFileTest.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/CustomServletDeployer.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/osgi/Activator.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java
=> chore: update-copyright-14.8 [skip ci]

platform-servlet-containers-tests/felix-jetty/src/test/java/com/vaadin/platform/wait/WaitHttpIT.java, vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java, vaadin-core/src/test/java/VersionsFileTest.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/CustomServletDeployer.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/osgi/Activator.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java
=> chore: update-copyright-14.7 [skip ci]

vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java, vaadin-core/src/test/java/VersionsFileTest.java, vaadin-platform-gradle-test/src/test/java/com/vaadin/platform/gradle/test/AbstractPlatformTest.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeDeviceTest.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeOfflineIT.java, vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ComponentsIT.java, vaadin-platform-servlet-containers-tests/bnd-tools-test/src/test/java/com/vaadin/platform/wait/WaitHttpIT.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/CustomServletDeployer.java, vaadin-platform-test/src/main/java/com/vaadin/platform/test/osgi/Activator.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/AbstractPlatformTest.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java
=> chore: update-copyright-21.0 [skip ci]

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
=> chore: update copyright header [skip ci]

scripts/generator/templates/template-release-notes.md
=> chore: mention JDK 17 support in 14.8 [skip ci]

versions.json
=> chore: Update Quarkus to 1.0.0.beta1

versions.json
Align the versions on 14.8 branch changed [here (Grid)](https://github.com/vaadin/flow-components/commit/1434086cbd9bedcc4560345b7c17b93d2637dea2) and [here (Dialog)](https://github.com/vaadin/flow-components/commit/24270910ecd85f836351975516edf907aacbde87) in Flow Components.
=> chore: update Dialog and Grid on v14.8

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
=> chore: align jackson version with flow updates

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
align the version used in flow
=> chore: update betybuddy version for OSGi test

vaadin-gradle-plugin/gradle/wrapper/gradle-wrapper.properties, vaadin-platform-gradle-test/gradle/wrapper/gradle-wrapper.properties
=> chore: upgrade gradle to 7.3

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
align the version with flow project
=> chore: Update byte-buddy to 1.12.1

versions.json
align with https://github.com/vaadin/flow-components/commit/cbb662c09de470d8c0bf3aa030d45cc38e6bdc18
=> chore: update context-menu and menu-bar versions

versions.json
=> chore: update flow version in V14.8

versions.json
update CE to 4.0.0.rc1
update legacy component to 1.0.0.rc1
=> chore: update CE and legacy component versions

pom.xml, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core-jandex/pom.xml, vaadin-core/pom.xml, vaadin-jandex/pom.xml, vaadin-platform-gradle-test/gradle.properties, vaadin-platform-hybrid-test/pom-dev-mode.xml, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
=> chore: update project to 23.0-SNAPSHOT

scripts/generator/templates/template-release-notes.md
Correct me if I’m wrong, but this template will be used for the V22 stable release.
=> Add special thanks to V22 release notes [skip ci]

versions.json
=> chore: update quarkus to 1.0.0

versions.json
upgrade CE to 4.0.0
upgrade legacy component to 1.0.0
=> chore: update CE and legacy component to final

versions.json
upgrade flow to 2.7.6
upgrade flow-spring to 12.4.1
=> chore: update dependencies in 14.8

versions.json
Update OSGi to compatible version.
=> Update OSGi to compatible version

scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
fixes needed after flow fixes https://github.com/vaadin/flow/commit/a01be8464d30a0e8f9be6a4bf67181d2f81f7aab
same fix has been applied to V22 branch in https://github.com/vaadin/platform/commit/893d37f39495938041e732451c0e78340f7adb27
=> chore: add provided dependecies

README.md
=> chore: update supported versions [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
=> chore: correct the osgi version in note template [skip ci]

.github/workflows/greetings.yml
Use "Vaadin" instead of "Vaadin Platform".
=> Update greetings.yml [skip ci]

pom.xml, vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java, vaadin-quarkus-extension/pom.xml
=> Add Vaadin Quarkus Extention

versions.json
related discussion https://vaadin.slack.com/archives/CACKS4075/p1644313284018279
=> chore: remove polymer version

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/resources/vaadin-featureflags.properties, vaadin/pom.xml, versions.json
Adds the map component to the platform.
=> chore: add map component to platform

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
=> chore:use hilla in releasenote template

scripts/generator/templates/template-release-notes-prerelease.md
=> chore: update release note after spring migration [skip ci]

versions.json
=> chore: update @vaadin/bundles package version

scripts/generator/templates/template-release-notes.md
=> chore: remove already fixed issue from template [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md
=> chore: remove the link for spring addon. [skip ci]

pom.xml
=> Chore: update parent project to 2.0.5 (CP: 14.8)

scripts/generator/templates/template-release-notes.md
Fixes: https://github.com/vaadin/flow/issues/13358
=> fix: Update web server compatibility info [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
Classic Components are more related to MPR.
=> Classic Components are not part of the Design System [skip ci]

versions.json
=> chore: update CE to 5.1.0.alpha2

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
=> chore: Update jackson-databind version

README.md
=> chore: add some badges to the readme [skip ci]

scripts/generator/templates/template-release-notes.md
=> chore: mention firefox ESR in release note [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml, versions.json
Adds `vaadin-portlet` plugin to the `vaadin` BOM.
=> chore: Add vaadin-portlet to platform

versions.json
=> chore: Upgrade CE to 5.0.2

versions.json
=> chore: upgrade CE to 5.1.0.beta2

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
=> chore: update license-checker for osgi test

scripts/generator/templates/template-release-notes.md
update release note. 
add collapsible section in the note
=> chore: update releasenote template for final release [skip ci]

scripts/generator/templates/template-release-notes.md
=> Update template-release-notes.md [skip ci]

hilla/pom.xml, scripts/generator/templates/template-hilla-bom.xml, scripts/generator/templates/template-hilla-maven-plugin-pom.xml, vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java
Hilla artifacts are modified to include the multi-module generator and engine.
Closes #3157
=> Hilla: add engine to platform artifacts

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
created as draft since probably it needs more work, let's see what happens in ci
=> chore: do not run chrome tests in sauce (#3182) (CP 14.8) 

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
=> update license checker to 1.7.2

hilla-spring-boot-starter/pom.xml, vaadin-spring-boot-starter/pom.xml
=> chore: Update spring boot version to 2.7.3

pom.xml
Update the Hilla platform artifact version.
=> chore: update hilla.version to 1.3-SNAPSHOT

scripts/generator/templates/template-vaadin-spring-bom.xml, versions.json
together with PRs 
FC:
https://github.com/vaadin/flow-components/pull/3933
https://github.com/vaadin/flow-components/pull/3934
WC:
https://github.com/vaadin/web-components/pull/4844
=> chore: remove the deprecated `@vaadin/vaadin-` prefix

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, versions.json
Updated web components to 24.0.0-alpha1.
- Version bump
=> chore: update web components to v24.0.0-alpha1

versions.json
Added missing `@vaadin/overlay` that replaces `@vaadin/vaadin-overlay` removed in #3383
- Internal change
=> chore: add new overlay package to versions.json

versions.json
=> bump testbench to 9.0.0.alpha4

versions.json
Note: MPR-V7 not ready yet, so not added.
=> chore: Add MPR-V8 dependency again

versions.json
=> chore: upgrade CDI to 14.1.0.beta1

pom.xml, versions.json
keep version in sync https://github.com/vaadin/flow/commit/8169657a2e551223e2ee7b54a23a3e253c50402a
=> chore: update spring dependency and remove extra repo

scripts/generator/templates/template-hilla-maven-plugin-pom.xml, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
flow reference: https://github.com/vaadin/flow/blob/master/flow-plugins/flow-maven-plugin/pom.xml#L71
hilla reference : https://github.com/vaadin/hilla/blob/a3ae038aaeefb62879bf570b0b4760d033d530f0/packages/java/maven-plugin/pom.xml#L44
=> chore: keep dependency version sync with its project [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml, versions.json
=> chore: fix typo for kubernetes [skip ci]

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, versions.json
=> chore: add azure kit to release note [skip ci]

versions.json
- MPR 6.1.0  
- OSGi 8.1.0 
- portlet 2.1.0 
- CDI 14.1.0
=> chore: update flow addons for Vaadin 23.3.0

versions.json
- Collaboration-engine 5.3.0
- Classic-components 23.3.0
- observability-kit 1.0.0
- SSO-kit 1.0.0
- azure-kit 1.0.0
- k8t-kit 1.0.0
=> chore: update kits and projects for V23.3.0 release

scripts/generator/templates/template-hilla-maven-plugin-pom.xml
this dependency should come from flow as transitive dependency.
=> fix: remove commons-io dependency declaration

versions.json
MPR dependencies update to 7.0.0.alpha2, brought back mpr-v7
=> deps: MPR update to 7.0.0.alpha2, added mpr-v7

versions.json
=> dep: MPR version update to 6.1.1

versions.json
=> MPR version update to 6.0.4

versions.json
=> dep: MPR update to 2.2.13

scripts/generateBoms.sh, scripts/generator/generate.js, scripts/generator/templates/template-dev-bundle-pom.xml, versions.json
generate dev bundle using the flow.version from versions.json
=> chore: generate dev bundle pom file

.gitignore
=> chore:add dev-bundle.pom to ignore [skip ci]

versions.json
bump cdi to 15.0.0.alpha2 and quarkus to 2.0.0.alpha3
=> dep: bump cdi and quarkus

versions.json
This updates the version of the `kubernetes-kit-starter` dependency to 1.0.2.
=> Update kubernetes kit 1.0.2

scripts/generator/templates/template-dev-bundle-pom.xml
Dev-bundle should contain all vaadin components
=> chore: add spreadsheet to dev bundle

versions.json
Dependency update of MPR to 7.0.0.alpha3
=> dep: bump MPR to 7.0.0.alpha3 [skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml
=> chore: add vaadin-testbench-junit5 into bom

versions.json
=> dep: quarkus bump to 2.0.0.alpha4

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
=> chore: add DSP to release note [skip ci]

pom.xml
after https://github.com/vaadin/hilla/pull/757
=> chore: update hilla.version 2.1-SNAPSHOT

pom.xml, scripts/generator/templates/template-dev-bundle-pom.xml, vaadin-platform-sbom/pom.xml, vaadin-platform-test/pom-dev.xml, vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java
This adds a new module so as we also run smoke tests in dev-mode.
It also adds a test for checking that in dev-mode a fresh project uses the shipped bundle instead of running npm install and compiling frontend
=> test: add module for testing in dev-mode, and add DefaultDevBundleIT

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
=> chore: temporally disable safari test for V24.1

pom.xml
align versions https://github.com/vaadin/flow/blob/main/pom.xml#L87...L90
=> chore: align spring dependencies with flow

.github/workflows/pit.yml
=> chore: inputs has a limit of 10 [skip ci]

versions.json
=> chore:keep main branch versions being updated

pom.xml
=> chore: update spring-boot to 3.0.5 [skip ci]

pom.xml
matching with flow https://github.com/vaadin/flow/commit/676ea9f0d9a7e972e9b6204315f990c359a1f488
=> Upgrade SB to 2.7.10 (v23.3) [skip ci]

versions.json
This reverts commit 1753cb49e29a9ed40efb3616c55f61bc183f5932.
=> chore: keep the same license-checker version with flow 23.2.11 [skip ci]

versions.json
Add the new [a11y-base](https://github.com/vaadin/web-components/tree/main/packages/a11y-base) package to versions.json
=> chore: add a11y-base JS package

scripts/generator/templates/template-vaadin-bom.xml, versions.json
=> chore: update license-checker to 1.12.3 (V14)

vaadin-platform-hybrid-test/frontend/routes.ts, versions.json
matching with flow change https://github.com/vaadin/flow/commit/4bad7bda3ce96de33b0baad24fd69652538a39e1
=> chore: fix the import for hybrid test mode

pom.xml
=> chore: update spring.boot to 3.0.6

versions.json
Pre-release for Flow 9.1.0.alpha1
=> chore: bump quarkus to 1.0.1.alpha1

scripts/generateAndCheckSBOM.js
=> chore: Fix sbom build [skip ci]

scripts/generator/templates/template-prod-bundle-pom.xml, vaadin-prod-bundle/src/main/resources/vaadin-featureflags.properties
Fixes https://github.com/vaadin/flow/issues/16887
=> fix: Include all parts of side-nav in production bundle

scripts/generateAndCheckSBOM.js, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
Update plugin versions used
in vaadin-maven-plugin.
Fixes vaadin/flow#16881
=> fix: update plugin versions

versions.json
=> chore: Update CDI, Spring and Quarkus versions

hilla-dev/pom.xml, hilla-react-spring-boot-starter/pom.xml, hilla-react/pom.xml, hilla-spring-boot-starter/pom.xml, hilla/pom.xml, pom.xml, scripts/generator/templates/template-hilla-bom.xml, scripts/generator/templates/template-servlet-containers-tests-pom.xml, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-test/pom.xml
=> chore: group platform modules in a profile, remove gradle module activation rule (CP: 24.1)

scripts/generator/templates/template-hilla-bom.xml
=> chore: fix naming in hilla-bom [skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml
Add dependency management for flow-webpush to the platform bom
=> Add flow-webpush package version to platform bom

vaadin-dev-bundle/src/main/resources/vaadin-featureflags.properties, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, versions.json
feature flag change in flow has not been released yet.. let us use snapshot version
=> chore: remove side-nav feature flag from platform

pom.xml
Fixes https://github.com/vaadin/platform/issues/4522
=> chore: bump vaadin-parent versiont o 2.2.1 [skip ci]

.github/workflows/sbom.yml
* disable bomber by default in  sbom.yml
=> disable bomber by default in  sbom.yml [skip ci] (#4560) (CP 23.3)

.github/workflows/sbom.yml, scripts/generateAndCheckSBOM.js
* disable bomber by default in  sbom.yml
=> disable bomber by default in  sbom.yml [skip ci] (#4560)

scripts/generateAndCheckSBOM.js, scripts/generator/templates/template-vaadin-bom.xml, vaadin-platform-sbom/pom.xml, versions.json
This adds AppSec Kit to the BOM.
=> Add appsec-kit to the BOM

pom.xml
=> chore: update spring-boot to 3.1.5 (CP :24.1)

.github/workflows/sbom.yml
this version will suppress the form-filler FP
=> update dependency+check plugin to 8.4.2 [skip ci]

.github/workflows/sbom.yml
This reverts commit db8f52ffc21173a8d2f99b7d9e9c995b192ed97e.
=> Revert "chore: enable the Bomber scanner again [skip ci]"

versions.json
=> use form-filler 1.0.1 [skip ci]

vaadin-gradle-plugin/build.gradle
=> chore: add dev and prod bundle to gradle plugin

vaadin-gradle-plugin/build.gradle
=> chore: add dev and prod bundle to gradle plugin (#4674) (CP: 24.1)

scripts/generateAndCheckSBOM.js, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java, versions.json
* fix: Add DnD Connector to prod bundle
* use flow 24.3-SNAPSHOT
* Add the FP report for sbom
=> fix: Add DnD Connector to prod bundle (#4686)

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, versions.json
https://github.com/vaadin/flow/commit/c63f3df377bf350ec4d766bea8f84e81a3002df9
=> chore: add rangeInput to componentView

scripts/generateAndCheckSBOM.js
wait for the update from https://github.com/jeremylong/DependencyCheck/issues/6107
=> chore: pin dependency-check-maven verison to 8.4

pom.xml, scripts/generateAndCheckSBOM.js
=> upgrade springboot to 3.1.6 (#4728)

scripts/generateAndCheckSBOM.js, versions.json
Related to https://github.com/vaadin/flow/issues/18149
Same as #4745 but for `23.4` branch.
- Bugfix
=> fix: add missing vaadin-overlay npm package version (23.4)

versions.json
This updates Collaboration Kit to 6.2.0 to be included in V24.3
=> Update Collaboration Kit to 6.2.0

scripts/generateAndCheckSBOM.js, scripts/generator/templates/template-release-notes-maintenance.md, vaadin-spring-boot-starter/pom.xml
* chore: use logback-* 1.2.13 in V23.*
* Update template-release-notes-maintenance.md [skip ci]
=> chore: use logback-* 1.2.13 in V23.* [skip ci] (#4777)

.github/workflows/sbom.yml, scripts/generateAndCheckSBOM.js
* chore: update dependency-check to use 9.0.0
* Update sbom.yml
=> chore : update dependency-check to use latest (#4731) (CP: 23.3)

pom.xml
=> update springboot to 3.1.7 (24.2)

scripts/generateAndCheckSBOM.js
* Add description to white list and show cpes
* Separate error vulnerabilities from known in report
* remove unused imports and show known and actual vulnerabilities in different blocks
=> Add description to white list and show cpes [skip ci] (#4849)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
fix test after flow-components commit https://github.com/vaadin/flow-components/pull/5881
=> test: update the grid contextmenu test after flow-components fix

versions.json
=> deps: bump copilot to 24.3.4

scripts/generator/templates/template-vaadin-bom.xml, versions.json
* update license-checker to 1.12.4
* update jna to 5.14.0
=> update license-checker to 1.12.4 (#4901) (CP:23.4)

versions.json
=> chore: Copilot bump to 24.3.5

versions.json
=> upgrade spring-addon to 19.1.3

versions.json
=> chore: Copilot version update to 24.3.6

scripts/generateAndCheckSBOM.js
add description for this exclusion
=> sbom: suppress the jcef report

scripts/generator/generate.js, versions.json
related to #4936 
add react-components to vaadin-core-versions.json
add react-components-pro to vaadin-versions.json
depends on vaadin/react-components#229
=> draft: add react-component to versions.json

scripts/generator/generate.js, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml, vaadin-dev/pom.xml
=> draft: repackage vaadin-maven-plugin

scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml
=> workaround: use full path to the gradle plugin

versions.json
=> chore: update testbench to 9.2.2

scripts/generator/templates/template-dev-bundle-pom.xml, vaadin-dev/pom.xml
=> refactor: rename hilla-dev-mode to hilla-dev

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-internal/pom.xml
add flow-react into core-internals
Requires vaadin/flow#18710
=> feat: add flow-react module

scripts/generator/templates/template-dev-bundle-pom.xml, scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-dev/pom.xml, vaadin-gradle-plugin/build.gradle, vaadin-spring-boot-starter/pom.xml
this will work after https://github.com/vaadin/hilla/pull/2072
=> chore: fix after hilla artifacts renaming

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
copilot source is in a private repo. release note will be available after stable release
=> chore: mention hilla and copilot in the release note [skip ci]

versions.json
=> use hilla alpha8

versions.json
bump Copilot version update to 24.4.0.alpha6
=> chore: Copilot version update to 24.4.0.alpha6

hilla-react/pom.xml, hilla-spring-boot-starter/pom.xml, hilla/pom.xml, pom.xml, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-package.json, vaadin-core-jandex/pom.xml, vaadin-core/pom.xml, vaadin-jandex/pom.xml, vaadin-platform-gradle-test/gradle.properties, vaadin-platform-hybrid-test/pom-dev-mode.xml, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-sbom/pom.xml, vaadin-platform-test/pom.xml, vaadin-quarkus-extension/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
leave hilla version as 1.4 for now.
=> chore: upgrade to 23.5-SNAPSHOT

versions.json
=> dep: Copilot 24.4.0.alpha9

versions.json
bump Copilot to 24.4.0.alpha15
=> deps: bump Copilot to 24.4.0.alpha15

versions.json
=> upgrade copilot to 24.4.0.alpha16

scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml
=> feat: Property to disable hilla task registration

scripts/generateAndCheckSBOM.js
This reverts commit 38e1ac2eb639dca99f23914836738d838be53d3c.
=> [Test SBOM] Revert "chore: disable bomber temporarily [skip ci] (#6536)"

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-internal/pom.xml, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-testbench-junit5/pom.xml, vaadin-testbench/pom.xml, versions.json
Added the new component coming to 24.5
- Feature
=> feat: add Popover component to platform

versions.json
=> chore: update ui-tests to 1.0.0.alpha3

versions.json
=> chore: upgrade CE to 6.3.0.alpha3

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-platform-sbom/pom.xml, versions.json
Add Feature Pack as part of the platform
- [ x ] Feature
=> feat: Add Feature Pack as part of the platform

scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
=> provide hilla-endpoint for javadoc generation[skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-internal/pom.xml, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-testbench/pom.xml, versions.json
This PR adds Dashboard component to platform.
=> chore: add dashboard component

versions.json
=> chore: Update featurepack to 24.5.1 [skip ci]

versions.json
=> Update CC to RC1

vaadin-dev/pom.xml
=> fix copilot snapshot netty dependencyConvergence failure

vaadin-platform-react-hybrid-test/src/main/frontend/views/home/deepend/deep.tsx, vaadin-platform-react-hybrid-test/src/test/java/com/vaadin/platform/react/test/FlowMainLayoutIT.java
Add test for layout not matching path part in hilla view
=> test: Add nested path that doesn't have a path match.

vaadin/pom.xml
this will need https://github.com/vaadin/flow-components/pull/7093 to be merged
=> chore: add spreadsheet to enforcer plugin test

versions.json
Update Feature Pack to 24.7.0.alpha2
- [ x] Feature
=> chore: Update Feature Pack to 24.7.0.alpha2

.github/ISSUE_TEMPLATE/prd.yml
Add Security review field to PRD template
=> Add Security review field to PRD template [skip ci]

vaadin-gradle-plugin/build.gradle
Part of vaadin/flow#18612
Continuation of vaadin/flow#21022
Continuation of vaadin/hilla#3288
=> feat: add support for Gradle configuration cache

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-components/pom.xml, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-testbench-junit5/pom.xml, vaadin-testbench/pom.xml, versions.json
Adds the Card component to the platform
- Feature
=> feat: add Card component to platform

versions.json
Update feature-pack 24.7.2
- [ x] Feature
=> Update feature-pack to 24.7.2

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-components/pom.xml, vaadin-dev-bundle/src/main/resources/vaadin-featureflags.properties, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/resources/vaadin-featureflags.properties, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-prod-bundle/src/main/resources/vaadin-featureflags.properties, vaadin-testbench-junit5/pom.xml, vaadin-testbench/pom.xml, versions.json
Adds the Master Detail Layout component to the platform
- Feature
=> feat: add Master Detail Layout component to platform

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
`vaadin-context-menu-overlay` hass been added recently on flow-components side https://github.com/vaadin/flow-components/commit/afb5bfbe71a48c414cdf50ffb14b5209d54ff0b7
=> test: fix component test after adding vaadin-context-menu-overlay

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-components/pom.xml, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-testbench-junit5/pom.xml, vaadin-testbench/pom.xml, versions.json
this needs https://github.com/vaadin/flow-components/pull/7416 to be merged.
related to #7580
=> feat: add markdown component to platform

vaadin-platform-react-hybrid-security-test/src/main/frontend/views/hilla/@layout.tsx
https://vaadin.slack.com/archives/C01EJJNMAC9/p1747122544446469
=> chore: remove one work around

scripts/generateAndCheckSBOM.js
fixes https://github.com/vaadin/platform/issues/7631
=> chore: upgrade sbom creation script [skip ci]

versions.json
=> chore: upgrade copilot 24.8.0.beta3

.gitignore, pom.xml, scripts/generateBoms.sh, scripts/generator/generate.js, scripts/generator/templates/template-vaadin-quarkus-pom.xml, vaadin-quarkus/vaadin-quarkus-extension-deployment/pom.xml, vaadin-quarkus/vaadin-quarkus-extension/pom.xml, vaadin-quarkus/vaadin-quarkus-extension/scripts/MetaDataReplacements.java
=> fix: add proper deployment module for quarkus extension (24.8)

.gitignore, pom.xml, scripts/generateBoms.sh, scripts/generator/generate.js, scripts/generator/templates/template-vaadin-quarkus-pom.xml, vaadin-quarkus/vaadin-quarkus-extension-deployment/pom.xml, vaadin-quarkus/vaadin-quarkus-extension/pom.xml, vaadin-quarkus/vaadin-quarkus-extension/scripts/MetaDataReplacements.java
* fix: add proper deployment module for quarkus extension
* fix script execution
* Try to use JAVA_HOME env var
* clenaup
* cleanup pom
* cleanup script
=> fix: add proper deployment module for quarkus extension (24.8) (#7804) (CP: main)

pom.xml
=> chore: bump spring-boot to 3.5.4

pom.xml, vaadin-platform-react-hybrid-security-test/src/main/java/com/vaadin/platform/react/test/security/SecurityConfig.java, vaadin-platform-react-hybrid-security-test/src/test/java/com/vaadin/platform/react/test/AbstractPlatformTest.java, versions.json
Fixes https://github.com/vaadin/platform/issues/7769
=> upgrade spring boot 4.0.0-M1

versions.json
Let's add Aura npm package so that it gets installed. No Flow component API yet, to be considered later.
- Feature
=> feat: add Aura npm package to versions.json for V25

scripts/generator/templates/template-release-notes.md
=> update supported servlet for vaadin 24 [skip ci]

versions.json
=> chore: upgrade testbench to 9.5.1
