vaadin-bom/pom.xml
=> Include com.vaadin:flow version in BOM

vaadin-bom/pom.xml, vaadin/pom.xml
Add components at newest versions.
=> Update flow version to alpha11

vaadin-bom/pom.xml, vaadin/pom.xml
Add correct repo urls.
Remove generated components dependency.
=> Add vaadin-valo-theme to platform distribution.

vaadin-bom/pom.xml, vaadin/pom.xml
=> Add one more flow component

vaadin/src/main/resources/README
=> Add README to avoid errors about an empty jar

vaadin-bom/pom.xml
update Flow to alpha17;
update vaadin-radio-button-flow to alpha4
update vaadin-tabs-flow to alpha5.
=> Update Flow and components version

vaadin-bom/pom.xml, vaadin/pom.xml
update flow version;
update components versions;
add vaadin-list-box-flow.
=> Update flow and components

vaadin-bom/pom.xml
=> Define slf4j version

vaadin-bom/pom.xml
=> Use new vaadin spring artifacts

vaadin-bom/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/143)
=> Use latest testbench elements

vaadin-core/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/144)
=> Use distinct names for each module

.gitignore, pom.xml, vaadin-bom/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-maven-plugin/src/site/site.xml, vaadin-platform-test/pom.xml
Versioned with the platform, includes flow-maven-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/145)
=> Vaadin Maven plugin

vaadin-bom/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/146)
=> Update Flow and component versions

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/147)
=> Use latest testbench

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/148)
=> Update version for vaadin-combo-box-flow and vaadin-overlay

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/149)
=> Use latest charts

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/150)
=> Use latest board

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/151)
=> Remove duplicate notification test

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/160)
=> Update Flow version to beta10

.travis.yml, pom.xml, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-test/pom.xml
Add missing snapshot repos to submodules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/162)
=> Generate javadocs separately.

vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/164)
=> Exclude vaadin-platform-test from deployment

README.md
Add a readme for the platform repo that contains the information from https://vaadin.com/platform in a different format. Fixes #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/168)
=> Initial version of platform readme

vaadin-bom/pom.xml, vaadin-platform-test/pom.xml
Also fixes scope for vaadin-testbench
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/170)
=> Use testbench BOM and update to beta10

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/174)
=> Add vaadin-addons so testbench-bom can be found

pom.xml, vaadin-bom/pom.xml, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-test/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/175)
=> Define repositories in parent instead of in each module

vaadin-bom/pom.xml
to match with the bower version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/178)
=> Update vaadin-overlay to 3.0.3

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/171)
=> Update flow and component version

README.md
Improve readme intro text, explaining how releases work.
Ping @paivisoinio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/182)
=> Improve intro text

vaadin-bom/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/183)
=> Update Flow, Spring addon and components

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/142)
=> Test Safari 10

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/184)
=> Update to testbench beta11

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/188)
=> Update flow version to rc1

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/185)
=> Update vaadin-components-testbench to Beta5

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/186)
=> Update Charts to 6.0.0.beta5

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/189)
=> Update Spring version

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/190)
=> Update to testbench rc1

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/193)
=> Update Charts to RC1

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/194)
=> Update Vaadin Board to rc1

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/196)
=> Update version for date-picker

vaadin-bom/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/195)
=> Match dependency versions with Bower

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/199)
=> Update flow, spring-addon and flow-components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/205)
=> Update flow and combo-box to 1.0.0.rc3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/206)
=> Update flow and date-picker

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/207)
=> Update flow to 1.0.0.rc5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/208)
=> Update Board for Flow to RC2

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/210)
=> Add spring-boot-starter to bom

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/213)
=> Update flow and components version to 1.0.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/211)
=> Update Pro components to final

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/214)
=> Update vaadin-upload java version

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/215)
=> Update bom template

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/221)
=> Stylised the readme and fixed broken link

pom.xml, versions.json
Fixes #216  
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/222)
=> Update component versions and remove add-ons repo

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/225)
=> Update the combobox version.

.gitignore, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/226)
=> Skip test module deployment.

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/227)
=> Update Flow, DatePicker and ComboBox

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/234)
=> Update vaadin-split-layout js version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/236)
=> Update Flow 1.0.3 and components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/238)
=> Update Designer 3.0.6

pom.xml, scripts/generator/templates/template-vaadin-bom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
Update charts to new minor
Add vaadin-confirm-dialog
Add vaadin-cookie-consent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/244)
=> Update versions and add new components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/247)
=> Update components to latest patch releases

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/249)
=> Use stable versions of new components

.travis.yml, scripts/checkForNonPinnedDependencies.sh
Note: the PR build will fail because there is a non-pinned dependency in master already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/246)
=> Check for non-pinned dependencies.

.travis.yml, scripts/checkForNonPinnedDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/250)
=> Check for non-pinned dependencies

.travis.yml, scripts/generateBoms.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/252)
=> Add script to generate boms

scripts/generateBoms.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/254)
=> Forward command line argument to generate.js

versions.json
Includes #259 and #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/260)
=> Update charts version to stable

scripts/generator/templates/template-vaadin-bom.xml, versions.json
Webjar dependencies are updated to match the web component releases in https://github.com/vaadin/platform/pull/247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/251)
=> Update Flow components to latest patch releases

versions.json
Fixes #263
Pick changes from #247 and #251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/268)
=> Update component versions to latest stable

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/267)
=> Add version for latest Gradle plugin for notes

scripts/generator/templates/template-release-notes.md, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/255)
=> Update release notes for V11 beta

pom.xml, vaadin-spring-boot-starter/pom.xml
Fixes #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/266)
=> Add module for `vaadin-spring-boot-starter`

scripts/generator/templates/template-release-notes.md, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/274)
=> Update Designer 3.1.0

scripts/generator/templates/template-release-notes.md
V10 is already stable, this paragraph doesn't apply
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/277)
=> Remove beta mentions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/279)
=> Update flow version to 1.0.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/281)
=> Update component versions for Flow 1.0

versions.json
(cherry picked from commit 2ab51e3f23f739829b88bdfde601a50b05f1375f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/280)
=> Update flow version to 1.0.4 (#279)

vaadin-spring-boot-starter/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/283)
=> Update vaadin-spring version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/282)
=> Update component versions for Flow 1.0 (#281)

vaadin-spring-boot-starter/pom.xml, versions.json
* Update vaadin-spring version
* Update versions.json
* Update spring-boot.version to match vaadin-spring
(cherry picked from commit 0770854f28c5c497c2bf1a48fccfbd8f6f8be855)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/284)
=> Update vaadin-spring version (#283)

versions.json
Updated Confirm dialog and cookie consent stable versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/289)
=> Update components for V11

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/288)
=> Update Flow and components to latest patch releases

versions.json
* Update Flow to 1.0.5
* Update component versions too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/292)
=> Update Flow and components to latest patch releases (#288)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/293)
=> Update Designer 3.1.1

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/300)
=> Skip javadoc for vaadin-platform-parent

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/305)
=> Update flow and flow-spring to the latest

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/309)
=> Update flow-spring to 10.0.4

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/299)
=> Clarify support wording in release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/311)
=> Update flow and components to latest prereleases

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/308)
=> Update Designer 3.1.2

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/314)
=> Skip javadoc for vaadin-platform-parent (#300)

vaadin-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/316)
=> Add material theme dependency to the vaadin-core project.

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/320)
=> Add Vaadin CDI add-on version into the vaadin-bom.

scripts/generator/templates/template-release-notes.md
Add changes done to the last public release noted.
Reworded to "Vaadin CDI Addon" for consistency.
`({{core.vaadin-cdi.javaVersion}})` should be used once the addon is added to the bom and versions.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/319)
=> Update release notes template

versions.json
Connected to https://github.com/vaadin/vaadin-core/issues/197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/302)
=> Pin internal dependencies

scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/321)
=> Update to stable Flow and Components' versions.

versions.json
Connected to https://github.com/vaadin/vaadin-core/issues/197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/298)
=> Add Polymer, shadycss, webcomponentsjs

versions.json
- vaadin-overlay
- vaadin-control-state-mixin 
- vaadin-development-mode-detector
- vaadin-element-mixin
- vaadin-themable-mixin
- vaadin-usage-statistics
Connected to https://github.com/vaadin/vaadin-core/issues/197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/296)
=> Add internal vaadin dependencies

versions.json
Connected to https://github.com/vaadin/vaadin-core/issues/197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/297)
=> Add iron- dependencies

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/322)
=> Match jsVersion with flow component base

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/323)
=> Update version for v12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/324)
=> Update vaadin-icons to stable version

scripts/generator/templates/template-vaadin-spring-bom.xml
Closes #328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/329)
=> Add context menu Flow wrapper.

scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/330)
=> Fix context-menu-flow groupId

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/332)
=> Update pro java version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/334)
=> Align js pinned version and actually used version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/339)
=> Update flow-spring version to 10.0.5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/340)
=> Update flow, CDI, grid and Icons

scripts/generator/templates/template-release-notes.md
Fixes  #327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/336)
=> Initial update for v12 release notes

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/326)
=> Add Material theme info to README

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/346)
=> Match iron-a11y-announcer, iron-icon, iron-media-query with webjars version

vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/347)
=> Update jetty version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/348)
=> Update Flow components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/342)
=> Update flow-spring version to 10.0.5 (#339)

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/356)
=> Pin license-checker

.travis.yml, scripts/checkForNonPinnedDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/312)
=> Change order of non-pinned dependencies checker

scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/361)
=> Added back vaadin-dialog exclusion

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/362)
=> Update Flow component versions.

versions.json
includes a fix for the loading indicator
https://github.com/vaadin/vaadin-combo-box-flow/releases/tag/2.0.0.beta2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/365)
=> Update vaadin-combo-box-flow to beta2

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/363)
=> Re-enable javadoc plugin when verifying PRs.

scripts/generator/templates/template-vaadin-bom.xml
should be after https://github.com/vaadin/platform/pull/362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/364)
=> Align pinned version with flow-component-base and pro

versions.json
Get into use pro components with latest flow and flow-components-base versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/367)
=> Update pro components versions

pom.xml, vaadin-core/pom.xml, vaadin-platform-javadoc/pom.xml
Fixes https://github.com/vaadin/platform/issues/275
Probably we should have a better module name, I can't come up with any better one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/285)
=> Generate javadoc for platform

scripts/generator/templates/template-release-notes.md, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/373)
=> Update release notes v12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/366)
=> Bump lumo-styles version to 1.3.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/376)
=> Update pro components to latest versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/378)
=> Use stable vaadin-board

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/379)
=> Advance Flow version to 1.2.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/380)
=> Update app layout to stable

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/383)
=> Update MPR versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/385)
=> Update to Crud 1.0.0 final

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/386)
=> Add new components to readme

vaadin-spring-boot-starter/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/388)
=> Update spring version boot starter

vaadin-core/pom.xml, vaadin/pom.xml, versions.json
This change is not breaking `vaadin` users, but fixes `vaadin-core`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/390)
=> Move app layout

versions.json
Update grid to latest release version  which is 2.1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/395)
=> Update Grid to 2.1.1

vaadin-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/397)
=> Add vaadin-context-menu-flow to vaadin-core

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/394)
=> Pin vaadin-overlay and vaadin-license-checker in vaadin

versions.json
Related to https://github.com/vaadin/flow-component-base/pull/90#issuecomment-437854904
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/396)
=> Revert minor version updates for v10

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/398)
=> Fix wrong version mode detector and usage statistics

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/399)
=> Revert minor version updates for v11 (#396)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/402)
=> Fix ComponentsIT for Safari 12

vaadin-spring-boot-starter/pom.xml, versions.json
10.0.6 and 2.0.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/404)
=> Update Spring-addon and Spring boot

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/406)
=> update charts version

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/408)
=> Fix ComponentsIT for Safari 12 (#402)

versions.json
Close https://github.com/vaadin/platform/pull/295 https://github.com/vaadin/platform/pull/389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/407)
=> Update maintenance versions

scripts/generator/templates/template-vaadin-bom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, versions.json
Close https://github.com/vaadin/platform/pull/401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/409)
=> Override all transitive dependencies v11

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/411)
=> Update board for v11

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/410)
=> Update board for v10

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/414)
=> Update pro component versions for v12

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/416)
=> Update required Jetty version

.travis.yml, scripts/verifyBowerDependencies.sh
Fixes https://github.com/vaadin/platform/issues/355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/382)
=> Compare bower and maven versions on each pr

versions.json
Update flow to 1.0.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/418)
=> Update Flow version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/417)
=> Update Pro components

versions.json
Update flow version from 1.2.0 to 1.2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/420)
=> Update Flow version to 1.2.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/425)
=> v12: Update app-layout component versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/426)
=> Update app-layout component versions

pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes.md, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/423)
=> Prepare for v13

versions.json
Fixes #427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/431)
=> Update tabs version for V10

versions.json
Fixes #427
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/430)
=> Update tabs version for V11

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/434)
=> Update components v10 versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/429)
=> Updating flow version to 1.2.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/438)
=> Updating flow-spring version to 10.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/441)
=> Update Gradle plugin version to 1.0.0.RC4

README.md, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/436)
=> Update components v13 versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/443)
=> Updating Flow version to 1.2.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/444)
=> Updating Flow version to 1.2.3 in master branch

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/447)
=> Update v12 components to latest maintenance releases

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/448)
=> Update v12 patch versions

versions.json
- ComboBox
- Grid
- ContextMenu
- IronList
- DatePicker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/450)
=> Updating components versions

scripts/generator/templates/template-vaadin-spring-bom.xml
This fix should be backported to v12 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/439)
=> Add missing flow-osgi to BOM

README.md, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, versions.json
- Updating components versions
- Adding `vaadin-time-picker-flow` component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/451)
=> Updating components versions and adding vaadin-time-picker-flow

scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/452)
=> Add missing flow-osgi to BOM for v12 (#439)

scripts/generator/templates/template-release-notes.md, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/455)
=>  Update Gradle plugin version to 1.0.0.RC4 (#441)

scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/453)
=> Move flow-osgi to vaadin-bom

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/457)
=> Update the vaadin-context-menu-flow version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/459)
=> Update crud version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/454)
=> Updating flow-spring version to 10.1.1 (#438)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/461)
=> Update vaadin-overlay to latest version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/463)
=> Update v12 dependencies

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/464)
=> Update v13 dependencies

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/466)
=> Update v12 select to latest patch release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/467)
=> Update v13 select to latest patch release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/472)
=> Update v10 checkbox to latest patch release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/470)
=> Update v12 checkbox to latest patch release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/475)
=> Update v11 checkbox to latest patch release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/474)
=> Update flow version to 1.0.7

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/477)
=> Bump themable mixin to next minor

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/476)
=> Update component versions

versions.json
* Update flow version to 1.0.7
* Update radio button version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/478)
=> Update flow version to 1.0.7 (#474)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/487)
=> Update Flow version to 1.3.0.alpha2

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Use Safari 11 instead of 12.
Similar to https://github.com/vaadin/vaadin-login-flow/pull/26/commits/e5b67efe7cf94d58807033e7e6f98f613ba3dad5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/482)
=> Fix IT tests v10

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Use Safari 11 instead of 12.
Similar to https://github.com/vaadin/vaadin-login-flow/pull/26/commits/e5b67efe7cf94d58807033e7e6f98f613ba3dad5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/481)
=> Fix IT tests v13

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/490)
=> Update Flow version to 1.0.8

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/489)
=> Update Flow version to 1.2.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/492)
=> Update components version with OSGi fix.

versions.json
Cherry-pick from https://github.com/vaadin/platform/pull/492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/498)
=> Update components version with OSGi fix. (#492)

scripts/generator/package-lock.json, scripts/generator/package.json, scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes.md, scripts/generator/test/creatorTest.js
Cherry-pick from #344 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/422)
=> Generate changes since previous version (#344)

.travis.yml
* Enable IT tests in travis build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/504)
=> Enable IT tests in travis build

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/507)
=> Update v12 components maintenance releases

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/509)
=> Update Flow version to 1.3.0.alpha3

.travis.yml, scripts/verifyBowerDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/421)
=> Verify bower dependencies pr v10

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/510)
=> Update Flow Spring version to 10.2.0.alpha1

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/512)
=> Enable IT tests in travis build (#504)

.travis.yml, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/verifyNpmDependencies.sh
From the [discussion](https://vaadin.slack.com/archives/C3TGRP4HY/p1544446367104200)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/456)
=> Verify npm dependencies

scripts/generator/src/creator.js, scripts/generator/test/creatorTest.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/518)
=> Change npm releases to use ^ instead of exact versions

scripts/verifyNpmDependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/517)
=> Use find-duplicate-dependencies to improve the message

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/519)
=> Update v13 usage statistics, mixins and Lumo

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/524)
=> Update Board for Flow to 2.2.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/527)
=> Pin stable grid and textfield

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/530)
=> Update flow-spring version to 11.0.0

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/520)
=> flow 1.3.0, and final vaadin-[component]-flow versions

README.md, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, vaadin-testbench/pom.xml, vaadin/pom.xml, versions.json
Ready to review and merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/533)
=> Add Grid Pro, restore Rich Text Editor for Flow

scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/534)
=> Put vaadin-accordion-testbench in test scope

scripts/generator/templates/template-release-notes.md, scripts/listBreakingChanges.js
Update release notes + tweak script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/532)
=> Update release notes for V13 beta

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/539)
=> Update vaadin-confirm-dialog to 1.1.1

scripts/generator/templates/template-vaadin-spring-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/540)
=> Remove unneeded exclusion

versions.json
Cherry picked from the commit of this PR https://github.com/vaadin/platform/pull/541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/545)
=> Update Gradle plugin version to 1.0.0.RC8

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/546)
=> Update Flow components versions in versions.json

scripts/generator/templates/template-vaadin-spring-bom.xml
(cherry picked from commit 8cefacd214ac340d57eebbd0218175a29fec0220)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/547)
=> Remove unneeded exclusion (#540)

README.md, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/544)
=> Add Select component

vaadin-core/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/549)
=> Move to correct artifact

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/536)
=> Fix release note wording for V13

versions.json
Including several fixes for Combo-Box for Flow and Grid performance improvement in Edge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/548)
=> Update components maintenance releases

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/551)
=> Update Flow version to 1.2.5

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/552)
=> Override webjars dependencies of new components

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/553)
=> Flow 1.0.9

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/555)
=> Update vaadin-components-testbench to version with BFP

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/554)
=> Update components flow integration

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/559)
=> Upgrade MPR version to 1.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/558)
=> Flow 1.4 + component patches (Pending grid 3.0.1)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/565)
=> Update Accordion for Flow to 1.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/566)
=> Update custom field java version

scripts/generator/src/creator.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/567)
=> Remove community indicator for Gradle plugin

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/570)
=> Update MPR version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/571)
=> Update components maintenance versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/574)
=> Update Flow version to 1.4.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/575)
=> Update Grid and ComboBox versions.

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/579)
=> Update vaadin-components-testbench version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/580)
=> Update vaadin-select to 2.0.4

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/581)
=> Pin vaadin-grid-pro and vaadin-confirm-dialog webjars

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/582)
=> Update vaadin-custom-field-flow to 2.0.2

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/584)
=> Prepare v14

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/445)
=> Update release notes about CDI and OSGi support

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/588)
=> Update vaadin-button java version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/592)
=> Bump versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/594)
=> Bump vaadin-combo-box-flow

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/595)
=> Update Charts to 6.2.2 and pin webjar (v14)

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/596)
=> Update Charts to 6.2.2 and pin webjar (v13)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/601)
=> Flow 1.5.0.alpha2

scripts/generator/templates/template-release-notes.md
* Add Maven archetypes (#603)
* Update New and noteworthy
* Update Breaking changes
* Update supported IDEs for Designer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/605)
=> Update release notes for V14

versions.json
Update flow to 1.4.3
Update vaadin-time-picker-flow to 1.1.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/600)
=> Update Flow and vaadin-time-picker-flow

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/602)
=> Update vaadin-time-picker-flow to 1.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/606)
=> Update flow-spring to 11.1.0.alpha1

scripts/generator/templates/template-release-notes.md
Fixes #603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/610)
=> Add Maven archetype to release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/611)
=> Bump grid-pro wc dependency

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/607)
=> Update flow version to 1.0.10

versions.json
Includes the fix for https://github.com/vaadin/vaadin-date-picker/issues/651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/613)
=> Bump date picker version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/615)
=> Update to app layout 2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/618)
=> Update vaadin-time-picker-flow to 1.1.2

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/616)
=> Update application servers list for 14

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/617)
=> Update flow, spring and timepicker-flow version

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/622)
=> Pin crud and rich-text-editor

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/629)
=> Bump checkbox-flow with BFP fix

.travis.yml, platform-servlet-containers-tests/pom.xml, vaadin-platform-test/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/627)
=> Update Flow to 2.0.0.beta1

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/631)
=> Add missing ContextMenu and sort alphabetically

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/630)
=> Update app-layout WC to 2.0.0-beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/632)
=> Update Flow to 2.0.0.beta2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/634)
=> Update vaadin-app-layout-flow to 2.0.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/635)
=> Update flow to 1.4.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/638)
=> Update app-layout to stable 2.0.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/633)
=> Update flow to 1.0.11

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/641)
=> Update grid-flow to 3.0.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/639)
=> Update cookie-consent to 1.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/642)
=> Bump Cookie Consent to 2.0.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/636)
=> Update vaadin-login-flow to 2.0.0.beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/650)
=> Bump Flow, Spring & CDI versions to RC

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/621)
=> Only run push validation on main branches

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/653)
=> pin cookie consent webjar

README.md, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, vaadin-testbench/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/655)
=> Update components v14 versions

.travis.yml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/637)
=> Run builds for both bower and npm modes

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-testbench/pom.xml, versions.json
Fixes #537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/597)
=> Replace vaadin-components-testbench with separate artifacts

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/658)
=> Added things to New and Noteworthy

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/663)
=> Update testbench-core version

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/661)
=> Supported Node.js Versions, tabs to spaces

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/665)
=> Update login WC to 1.0.1 (v13)

vaadin-core/pom.xml, vaadin-core/src/main/templates/com/vaadin/shrinkwrap/VaadinCoreShrinkWrap.java, vaadin/pom.xml, vaadin/src/main/templates/com/vaadin/shrinkwrap/VaadinShrinkWrap.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/674)
=> Renave project version to match npm convention when annotating shrink

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/677)
=> Update flow to 1.4.5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/676)
=> Update flow to 1.0.12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/680)
=> Update to testbench stable

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/682)
=> Remove ignore from test

versions.json
Related to https://github.com/vaadin/vaadin-form-layout-flow/issues/92
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/683)
=> V13: Update form layout WC to 2.1.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/684)
=> Update form layout WC to 2.1.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/690)
=> Update testbench to version with latest byte buddy

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/689)
=> V13: Update usage-statistics and dev-mode-detector

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/691)
=> V13 Update development-mode-detector to 2.0.2

vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/696)
=> Fix vaadin-maven-plugin goal in test module

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/697)
=> Update Flow and Spring

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/698)
=> Update web components to latest versions

versions.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/699)
=> Update components versions for beta3

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/685)
=> Added npm version

versions.json
Update Gradle plugin to 1.2 which supports Vaadin 14 (Bower mode)
Creating local branch for https://github.com/vaadin/platform/pull/693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/694)
=> Update Gradle plugin to 1.2 in master

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/700)
=> Update to latest tesbtench

scripts/generator/templates/template-release-notes.md
Added Framework and Components headers (as in https://vaadin.com/releases/vaadin-14).
Re-arranged the order of the lists. Added paragraph under New and Noteworthy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/701)
=> New and Noteworthy

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/702)
=> Update flow version to 2.0.0.

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/705)
=> Update CDI to 11.0.0 release

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/706)
=> Update Spring version to 12.0.0

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/703)
=> Added dependency snippet

vaadin-platform-javadoc/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/708)
=> Bump components versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/711)
=> Upgrade MPR version to 1.2.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/712)
=> Update tabs and custom-field versions to latest

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/714)
=> Update v13 components to latest versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/715)
=> Upgrade to Flow 1.4.6

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/716)
=> Update to latest app layout flow

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/709)
=> Added note about webpack-config.js

platform-servlet-containers-tests/felix-jetty/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/719)
=> Upgrade ci-sauce version to 1.138

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/717)
=> Upgrade MPR version to 2.0.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/720)
=> Bump flow version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/721)
=> Upgrade flow-spring version to 12.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/723)
=> Update development-mode-detector to 2.0.4

.travis.yml
Travis logs are getting too big. Trying to get maven to be less verbose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/727)
=> Added -B to mvn

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/728)
=> Upgrade Spring add-on version to 12.0.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/729)
=> Update vaadin-crud to 1.0.4

versions.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/724)
=> Update components versions for RC3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/730)
=> Upgrade Flow to version 2.0.2

versions.json
Crud still had issues with versions. This update should fix them. 
Waiting for release of flow version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/732)
=> Update crud to 1.0.5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/738)
=> Bump component versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/739)
=> Update version for vaadin-components-testbench

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/741)
=> Update crud versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/744)
=> Bump context-menu and menu-bar versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/745)
=> Update Flow version to 1.4.7

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/748)
=> Flow 2.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/750)
=> Upgrade Flow version to 2.0.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/751)
=> Update vaadin-text-field version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/759)
=> Update flow version to 2.0.5

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/757)
=> Use https for repositories

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/762)
=> Use https for repositories (#757)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/765)
=> Update Spring add-on version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/767)
=> V13: Bump component versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/768)
=> V10: Bump component versions

platform-servlet-containers-tests/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
Related to vaadin/platform#766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/769)
=> Use https for Maven repositories

scripts/generator/templates/template-vaadin-spring-bom.xml
Added to Flow in https://github.com/vaadin/flow/pull/6122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/771)
=> Include compatibility mode shorthand in the bom

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/772)
=> Bump vaadin-grid-flow

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/779)
=> Bump Flow version to 2.0.6

vaadin-platform-test/pom-bower.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/780)
=> added flow-server-compability-mode

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/783)
=> Added Migrating from Vaadin 10-13

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/786)
=> Bump Flow version to 2.0.7

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/788)
=> Bump Flow version to 1.4.8

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/790)
=> Update Java support

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/792)
=> Release notes for the final

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/798)
=> Update Flow to 2.0.8

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/793)
=> Changed the platform support time

scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/801)
=> Removed the known issues fixed by 14.0.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/802)
=> Update license checker to 2.1.1

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/805)
=>  Add instruction into ReadMe

scripts/generator/templates/template-release-notes.md, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/803)
=> Java 11 test

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/809)
=> Update Flow to 1.0.13

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/813)
=> Removed archived repos from Front-end

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/818)
=>  Update Flow to 2.0.9

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/817)
=> Update to Vaadin 14.1

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/819)
=> prepare master branch to 15.0

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/820)
=> Add condition to trigger travis build

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/821)
=> Update Spring addon to 12.0.4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/816)
=> Flow version to 2.1.0.alpha1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/825)
=> Flow version to 2.1.0.alpha1 (#816)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/822)
=> Update Spring addon to 12.0.4 (#821)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/827)
=> Bump to Flow 3.0.0.alpha1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/834)
=> Updated Flow to 2.0.10

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/849)
=> Update spring 12.0.5

scripts/generator/templates/template-vaadin-package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/848)
=> Set main file and align with vaadin-core

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/855)
=> Update App Layout to 2.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/857)
=> Update App Layout to 2.0.3 (V14.1)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/859)
=> Bump flow-spring version to 12.0.6

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/856)
=> Update App Layout to 2.0.3 (V14.0)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/861)
=> Bump Flow version to 2.0.12

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/862)
=> Update FLow version to 2.1.0-beta1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/853)
=> Update Flow to 3.0.0.alpha2

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml
This should be backported to 14.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/863)
=> Add flow dnd to the platform

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/864)
=> Update flow to 2.0.13

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml
* Add flow-dnd to bom
* Add flow-dnd to vaadin-core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/871)
=> Cherry-pick: Add flow dnd to the platform (#863)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/873)
=> Update Flow to 3.0.0.alpha3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/875)
=> Flow version 2.0.14

versions.json
Connected to https://github.com/vaadin/vaadin-grid/issues/1660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/876)
=> Bump grid version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/878)
=> Update versions of components

scripts/generator/generate.js, scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/877)
=> added a release notes template for the maintenance release

scripts/generator/generate.js, scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/881)
=> Maintenance release notes for 14.1

scripts/generator/generate.js, scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/879)
=> Maintenance release notes for 14.0

README.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, versions.json
Fixes vaadin/vaadin-router#398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/883)
=> Add Vaadin Router to the platform

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/884)
=> Update vaadin-cookie-consent flow version

vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/888)
=> Set clientSideMode to be false in platform tests

vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/890)
=> Remove duplicated plugin declaration (#887)

vaadin-platform-test/pom.xml
this was missing from the original post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/894)
=> Adds missing repo change

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/895)
=> Update vaadin-context-menu-flow to 3.0.3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/896)
=> Update vaadin-context-menu-flow to 3.0.3 for 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/897)
=> Update vaadin-context-menu-flow to 3.0.3 for master

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/898)
=> Update Flow to 3.0.0.alpha4

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/899)
=> Update @vaadin/vaadin-router to 1.5.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/900)
=> Bump flow to 2.1.0.beta2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/885)
=> Update components for 14.1

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/906)
=> Removed bower-it - profile

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/886)
=> Update components for v15

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/907)
=> Update Flow to 3.0.0.alpha5

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/910)
=> Upgrade flow version to 2.1.0.beta3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/911)
=> Flow 2.0.15

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/915)
=> Update spring to 12.1.0.beta1

platform-servlet-containers-tests/felix-jetty/pom.xml, pom.xml, vaadin-platform-test/pom.xml
this is just a redo for PR: https://github.com/vaadin/platform/pull/585
as there are quite many conflicts in the original PR.
fixes #562 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/908)
=> polish the pom

platform-servlet-containers-tests/felix-jetty/pom.xml, pom.xml, vaadin-platform-test/pom.xml
* polish the pom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/916)
=> polish the pom (#908)

scripts/generator/generate.js, scripts/generator/templates/template-release-notes-prerelease.md
Removed the parts for archetype, add instructions for prerelease repository. Fix #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/918)
=> Add release note template for prerelease

versions.json
Restart build once the artifact is visible in central
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/923)
=> Flow 2.0.16

versions.json
Cherry-pick from #915 for 15.0-SNAPSHOT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/925)
=> Update spring to 12.1.0.beta1 (#915)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/936)
=> Update components versions for 14.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/940)
=> Update Flow to 2.0.17

scripts/generator/templates/template-release-notes-maintenance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/943)
=> Add limitation to the maintenance release note

vaadin/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/941)
=> Update Flow to 3.0.0.alpha6

scripts/generator/src/creator.js, versions.json
* List components within a repository in release notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/949)
=> List components within a repository in release notes (#428)

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
Removed the reference to designer from the release notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/950)
=> Removed the reference to designer

.travis.yml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/947)
=> No need to run tests on IE11 and Safari 9 for V15+

.travis.yml, vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/945)
=> Create Production mode profile for further testing purpose

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
related to #953
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/956)
=> Remove Safari10 from the test browser set

.travis.yml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
partly related to #953
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/955)
=> Add production profile to V14

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/957)
=> Bump Flow version to 2.1.0.rc1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/959)
=> Update components v14.1 versions

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/963)
=> List new component in listbox repo

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/966)
=> Update Flow to 3.0.0.alpha7 and router 1.5.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/969)
=> Flow 2.1.0.rc2

scripts/generator/generate.js, scripts/generator/src/creator.js, scripts/generator/src/writer.js, scripts/generator/templates/template-modules-release-notes.md
Added "modules-release-notes.md" with all the release notes of the changed modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/970)
=> Components changes release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/971)
=> Flow 2.0.18

vaadin-maven-plugin/pom.xml
Fixes https://github.com/vaadin/platform/issues/776
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/967)
=> Remove extra artifactItem settings from plugin pom

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/976)
=> Update MPR version to 2.0.1

vaadin-maven-plugin/pom.xml
fixes #777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/974)
=> Remove generated files in source folder, when clean the project

scripts/generator/generate.js, scripts/generator/src/creator.js, scripts/generator/src/writer.js, scripts/generator/templates/template-modules-release-notes.md, vaadin-maven-plugin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/973)
=> Pick release note update and maven plugin packing fix

.travis.yml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/968)
=> Separate production mode profile 14.1

vaadin-maven-plugin/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/979)
=> Picks fix 14.1

vaadin-maven-plugin/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/980)
=> Picks fix 14.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/988)
=> Add cookieconsent to versions.json for 14.0

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/989)
=> Add cookieconsent to versions.json for 14.1

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/993)
=> Pin cookieconsent in vaadin-bom for 14.1

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/991)
=> Add cookieconsent to versions.json for 15.0

scripts/generator/templates/template-vaadin-bom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/992)
=> Pin cookieconsent in vaadin-bom for 14.0

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/994)
=> Update Nodejs version

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/997)
=> Bump v14.0 text-field versions

versions.json
This version contains a BFP fix for RichTextEditor in Dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/999)
=> Update vaadin-overlay version for 14.1

scripts/generator/src/creator.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1003)
=> Dont consider the sub-components when generating the changed parts

.travis.yml
* Testing - update Nodejs version
* correct the cookie-consent
* Test with minimal Nodejs requirement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1007)
=> Update Nodejs version (#994)

scripts/generator/templates/template-vaadin-bom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/982)
=> keep the versions in master branch being updated

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1008)
=> Update element-mixin and usage-statistics for 14.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1009)
=> Bump flow version to 2.1.0

vaadin-spring-boot-starter/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1011)
=> Bump Flow Spring version to 12.1.0

versions.json
This PR won't be green until there is a new version of `vaadin-spring:12.2.x`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1016)
=> Update Flow to 3.0.0.alpha8

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1018)
=> update to latest testbench

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1020)
=> Bump Flow version to 2.0.19

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1024)
=> Use lates vaadin-spring version

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1026)
=> Updated OSGi support to release notes

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1029)
=> Update license-checker to 2.1.2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1034)
=> Update CDI to 11.2.0.alpha1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1035)
=> Bump flow-spring version to 12.1.1

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1036)
=> Update flow to 3.0.0.alpha9

vaadin-spring-boot-starter/pom.xml, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1038)
=> update flow-spring to 13.0.0.alpha2

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1040)
=> update vaadin-spring to 13.0.0.alpha3

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1041)
=> Bump Flow version to 2.1.1

.travis.yml, platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generateBoms.sh, scripts/generator/package-lock.json, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/templates/template-vaadin-shrinkwrap-package.json, vaadin-core/pom.xml, vaadin-maven-plugin/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml, vaadin-testbench/pom.xml, vaadin/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1043)
=> Update Project to 14.2-SNAPSHOT

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1044)
=> Bump versions of Flow and CDI

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Dropped ComboBox and Edge test for master to get v15 alpha out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1058)
=> Dropped tests for master

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1059)
=> Fix the test View and related test

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1053)
=> update flow version to 3.0.0.alpha12

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1050)
=> Fix tests view and use id for finding element

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1055)
=> Update Spring add-on version to 12.1.2

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1060)
=> Fix tests view and use id for finding element (#1050)

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1054)
=> Update Flow version to 2.1.2

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1061)
=> re-enable Edge test

versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1065)
=> Mention vaadin-overlay in the release note
