vaadin/platform

vaadin-bom/pom.xml, vaadin-testbench/pom.xml
The default scope set in the bom is "test" so that it
is correct if you include dependencies one by one, but for
vaadin-testbench, the elements need to be included as "compile"
so that they are all included as part of vaadin-testbench (which still
is always included using "test")
=> Fix scopes for TestBench dependencies

vaadin-bom/pom.xml
which uses `<vaadin-grid> 5.0.0-beta5`
=> Use vaadin-grid-flow beta3

vaadin-core/pom.xml
Creates javadocs for all direct vaadin-core dependencies.
Unfortunately `<includeDependencySources>` only creates javadocs for direct
dependencies, so using the same in `vaadin` dependency would only produce
javadocs for board and charts. (I think) Vaadin-core would have to provide a sources
jar with sources from all dependencies so that javadocs could be created.
=> Create vaadin-core javadocs

pom.xml, vaadin-core/pom.xml
Force execution of javadoc plugin in parent build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/158)
=> Move javadoc common configuration to parent pom

pom.xml, vaadin-bom/pom.xml, vaadin-core/pom.xml
Cannot use flow dependency since aggregate javadocs are only provided for direct dependencies. flow artifact doesn't have any sourcs, so no javadocs for it. Thus, we should use direct flow-* artifacts as dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/180)
=> Fix missing javadocs for flow

versions.json
There is an important fix in latest context-menu related to correctly position it in the viewport
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/200)
=> Update versions.json to include latest context-menu

scripts/generator/templates/template-release-notes.md
Checked a diff between generated release notes and currently published release notes for 10.0.1.
Merging this would mean less manual changes in future releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/235)
=> Update release notes templates

scripts/generator/templates/template-vaadin-spring-bom.xml, versions.json
Added v7 and v8 versions of MPR. Those only belong in the platform BOM, not in vaadin nor vaadin-core dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/333)
=> Add multiplatform runtime to platform BOM

scripts/generator/generate.js, scripts/generator/src/creator.js, scripts/generator/src/writer.js, scripts/generator/templates/template-vaadin-bower.json, scripts/generator/templates/template-vaadin-core-bower.json, scripts/generator/templates/template-vaadin-core-package.json, scripts/generator/templates/template-vaadin-package.json, scripts/generator/test/creatorTest.js, versions.json
This change is made for https://github.com/vaadin/platform/issues/290
In this PR:
* Added `npmName` and `npmVersion` for each dependencies in `versions.json`
* Added package.json templates for vaadin/vaadin-core and vaadin/vaadin repositories: these files will replace the current package.json in the corresponding repository like we are doing now with bower.json
* Add a function to generate dependencies for `package.json` using the versions declared in versions.json
* It only adds dependencies which have `npmName`
* It uses `npmVersion` if founded, otherwise, `jsVersion` will be used
* Update components version
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/338)
=> Add package json templates

scripts/generator/templates/template-vaadin-bom.xml, scripts/verifyBowerDependencies.sh
I also removed the `license-checker` webjar replication in vaadin-bom template. There is no problem with the enforcer (as far as I checked), so I think it's better to not repeat it.
The license-checker version mismatch actually causes a problem in Designer https://github.com/vaadin/designer/issues/1866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/337)
=> Fix the verifyBowerDependencies script to check license-checker correctly

scripts/generator/templates/template-vaadin-bom.xml, versions.json
This PR downgrades `vaadin-grid` jsVersion since currently Flow can't support `vaadin-grid:5.2.0-beta2`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/349)
=> Align vaadin-overlay and vaadin-grid version

scripts/generator/templates/template-vaadin-bom.xml, versions.json
In addition to the Java version being pinned, also pin the JS version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/393)
=> Pin license checker

scripts/listBreakingChanges.js
A quick and dirty script for comparing major versions between master and some other branch. Produces output like this:
```
> node listBreakingChanges.js     
Breaking change! Current javaVersion version of vaadin-combo-box is 2.0.0.beta2, previous was 1.0.7
Breaking change! Current jsVersion version of vaadin-development-mode-detector is 2.0.0, previous was 1.1.0-beta1
Breaking change! Current jsVersion version of vaadin-element-mixin is 2.1.2, previous was 1.1.2
Breaking change! Current javaVersion version of vaadin-grid is 2.1.0.alpha2, previous was 1.0.5
Breaking change! Current jsVersion version of vaadin-usage-statistics is 2.0.1, previous was 1.1.0-beta1
Breaking change! Current javaVersion version of vaadin-designer is 4.0.0.alpha4, previous was 3.1.2
Breaking change! Current …
```
=> Add breaking change detector

scripts/generator/templates/template-release-notes.md
Make sure that the frontend installation instructions use the specific platform release version, and not latest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/468)
=> Fix the frontend installation instruction version

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Use Safari 11 instead of 12.
Similar to https://github.com/vaadin/vaadin-login-flow/pull/26/commits/e5b67efe7cf94d58807033e7e6f98f613ba3dad5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/480)
=> Fix IT tests v12

scripts/generator/templates/template-vaadin-bom.xml, versions.json
Updating to a version that is available also via Bower.
This is a breaking change for V12.
Fixes vaadin/flow#4944
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/496)
=> Update shadycss version

versions.json
Polymer update is needed for npm especially, as otherwise when installing `@vaadin/vaadin` user will get duplicated dependencies. I recommend stop pinning Polymer for npm completely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/493)
=> Update v12 components versions

versions.json
This includes a fix for combo-box Flow counterpart especially striking when used inside of a dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/503)
=> Update v12 overlay and text-field to latest patch releases

scripts/generator/generate.js, scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json, scripts/npmShrinkwrap.sh
Connected to #515
Files to be copied for releases:
- `vaadin-core-shrinkwrap-package.json` -> `package.json`
- `vaadin-core-npm-shrinkwrap.json` -> `npm-shrinkwrap.json`
- `vaadin-shrinkwrap-package.json` -> `package.json`
- `vaadin-npm-shrinkwrap.json` -> `npm-shrinkwrap.json`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/531)
=> Generate npm-shwinkwrap.json for vaadin-core as well

scripts/generator/templates/template-release-notes.md
This should be applied to any v13 and v12 releases. And upcoming releases too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/577)
=> Add web sockets in OSGi known limitation

versions.json
Somehow V13 included a version of time-picker-flow that has min/max APIs with a time-picker version that didn't (1.1). This PR upgrades the time-picker from 1.1 to 1.2.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/599)
=> Bump versions

vaadin/pom.xml
Fixes https://github.com/vaadin/platform/issues/604
Added the require upper bound deps rule, described in http://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html. In my tests, it was able to catch the problem described in https://github.com/vaadin/platform/issues/604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/608)
=> Add requireUpperBoundDeps rule

versions.json
Fix for BFP https://github.com/vaadin/vaadin-material-styles/issues/85 ("Blank screen and JavaScript syntax errors in IE11 when using Material theme")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/686)
=> V13: Update material styles to 1.2.3

vaadin-platform-test/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/692)
=> Removed a ant copy as un-necessary.

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
There is a known issue in split-layout that when it is placed in a vertical-layout it jammed and its height becomes zero. The workaround to fix it is to set `flex` CSS attribute to `none`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/695)
=> Fix splitLayoutIsRendered test

versions.json
Fix for BFP https://github.com/vaadin/vaadin-material-styles/issues/85 ("Blank screen and JavaScript syntax errors in IE11 when using Material theme")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/687)
=> Update material styles to 1.2.3

platform-servlet-containers-tests/felix-jetty/pom.xml
It was different from other modules and caused an error in platform build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/718)
=> Upgrade ci-sauce version to 1.138

scripts/generator/templates/template-release-notes.md
Firefox ESR is not considered as evergreen and therefor is not officially supported. (PM decision)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/735)
=> Added a note about Firefox ESR

scripts/generator/templates/template-release-notes.md
Firefox ESR is not considered as evergreen and therefor is not officially supported (PM decision).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/733)
=> Added a mention about Firefox ESR

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
Computed height in Chrome 76 changed resulting in different number of items rendered
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/773)
=> Remove magic number from iron list items assertion

platform-servlet-containers-tests/felix-jetty/pom.xml, platform-servlet-containers-tests/pom.xml, pom.xml, scripts/generator/templates/template-vaadin-bom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-platform-javadoc/pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin/pom.xml
- Use http when downloading felix dependency
- Use http for the vaadin.com url in pom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/770)
=> Say no to http (master)

.gitignore
Otherwise when building platform locally plenty of untracked files and folders show in git status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/778)
=> Update .gitignore to skip files that are not in source control

vaadin-core/pom.xml, vaadin/pom.xml
Previously javadoc and sources jars were not required but now
vaadin and vaadin-core have a shinkwrap class and extra artifacts
are required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/791)
=> Add javadoc and sources plugins to vaadin and vaadin-core

scripts/generator/templates/template-vaadin-bower.json, scripts/generator/templates/template-vaadin-package.json
This change was initially done and approved in https://github.com/vaadin/vaadin/pull/50
But it was overwritten in following release https://github.com/vaadin/vaadin/commit/15d68d9b82adcfa28a45596e600bb5a252a46902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/815)
=> Add entry point files for `vaadin` npm and bower artifacts

scripts/generator/templates/template-vaadin-bower.json, scripts/generator/templates/template-vaadin-package.json
This change was done and approved in https://github.com/vaadin/vaadin/pull/50
But it was overriden in following release https://github.com/vaadin/vaadin/commit/15d68d9b82adcfa28a45596e600bb5a252a46902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/824)
=> Add entry point files for `vaadin` npm and bower artifacts (#815)

vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml
warning has been logged in builds.
```
[Step 3/7] [WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-antrun-plugin @ com.vaadin:vaadin-platform-test-npm-mode:[unknown-version], /opt/agent/work/2d6ac34f9c1666e9/vaadin-platform-test/pom.xml, line 345, column 21
``` 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/887)
=> Remove duplicated plugin declaration

pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml
This should improve the performance of the initial repository scanning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/891)
=> Correct the repository order defined in the POM

pom.xml, vaadin-platform-test/pom-bower.xml, vaadin-platform-test/pom.xml, vaadin-spring-boot-starter/pom.xml
This should improve the performance of the initial repository scanning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/893)
=> Correct the repository order defined in the POM (#891)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
https://github.com/vaadin/skeleton-starter-flow/pull/255 
Fixes original issue #921 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/975)
=> Moved usage statistic test from starters

scripts/generator/src/creator.js, scripts/generator/test/creatorTest.js, versions.json
Added vaadin-router, vaadin-themable-mixin, vaadin-lumo-styles, vaadin-material-styles to the list of changed modules. Change also applies to mashup of release notes.
Also changed the link of MPR to "multiplatform-runtime" from the incorrect "cdi".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/983)
=> Release notes changes modules

scripts/generator/src/creator.js, scripts/generator/test/creatorTest.js, versions.json
Added vaadin-themable-mixin, vaadin-lumo-styles, vaadin-material-styles to the list of changed modules. Change also applies to mashup of release notes.
Also changed the link of MPR to "multiplatform-runtime" from the incorrect "cdi".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/984)
=> Release notes changes modules (cherry-pick to 14.1)

scripts/generator/src/creator.js, scripts/generator/test/creatorTest.js, versions.json
Added vaadin-router, vaadin-themable-mixin, vaadin-lumo-styles, vaadin-material-styles to the list of changed modules. Change also applies to mashup of release notes.
Also changed the link of MPR to "multiplatform-runtime" from the incorrect "cdi".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/986)
=> Release notes changes modules (cherry-pick to 14.0)

scripts/generator/templates/template-vaadin-bom.xml, versions.json
Also moved `cookieconsent` to `vaadin` as it is used by Pro component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/995)
=> Update components versions for 14.1

vaadin-platform-test/pom.xml
Fixes: https://github.com/vaadin/platform/issues/903.Flip the flag to enable tests running in v15 clientSideMode
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/985)
=> CCDM: run tests in v15

versions.json
This version ensures 14.0 users don't get `vaadin-usage-statistics` 2.1.0 (so they get 2.0.x instead)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1010)
=> Update element-mixin version for 14.0

scripts/generator/templates/template-release-notes.md
Removed IE11 and adjusted Safari support to version 13.
Part of vaadin/flow#6856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1096)
=> Update browser support release notes for V15

versions.json
This is a PR for 14.1 and it contains a Checkbox with a fix for incorrect `console.warn`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1113)
=> Bump checkbox and select versions

versions.json
This should help to get rid of duplicated dependencies problem.
The main cause is that `vaadin-button-flow` 3.0.0.alpha1 is released with `2.2.2` but the version specified on master is incorrectly set to `2.2.1` which results in duplicate button versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1116)
=> Update button and overlay versions

versions.json
This contains 2 bug fixes to vaadin-custom-field web component:
- 99e73b4 fix: add small theme variant (#69, #70)
- 72023bd fix: label styles for disabled and readonly states (#30, #68)
Make label styles consistent with vaadin-text-field when using the attribute `disabled` or `readonly` on the custom field. This only adds the styles for custom field label. The attributes are not automatically synchronized between custom field and any child components.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1120)
=> [14.1] Bump custom field versions

pom.xml
Current master build failed on JDK 10 and later, this is caused by using `maven-compiler-plugin` version:3.1 (this is the default version used in TC, check from https://bender.vaadin.com/viewLog.html?buildId=120679&buildTypeId=VaadinPlatform_ReleasePlatformSnapshotOracleJdk11&tab=buildLog&branch_VaadinPlatform_PlatformSnapshotJDKsTesting=%3Cdefault%3E&_focus=551.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1130)
=> Make compiler-plugin to use source/target level 8

versions.json
This has been removed from flow 3.0 as it is needed when supports the old browsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1132)
=> Remove webcomponentsjs from version.json

pom.xml
* Make compiler-plugin to use source/target level 6
Current master build failed on JDK 10 and later, this is caused by using `maven-compiler-plugin` 3.1 (this is the default version.)
* Update version to 1.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1134)
=> Make compiler-plugin to use source/target level 8 (#1130)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
referred ticket has been solved, so we should remove the workaround
Fixes #1100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1135)
=> Remove the workaround for ironListStyles.css

scripts/generator/src/creator.js
Registering bower package names is not supported anymore.
Bower dependencies can still be used by using the user/org name of the github repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1238)
=> Add github owner prefix for vaadin-date-time-picker

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml
Also, remove known issues of OSGi from release notes
There is no `flow-osgi` 3.0 or higher at the moment. It should have been removed from Vaadin 15 too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1249)
=> Remove flow-osgi from vaadin-bom

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml
* Remove flow-osgi from vaadin-bom
* Remove known issues of OSGi from release notes
(cherry picked from commit 8a37b4f8cf2d28901cad2a6a0361dbb88aa8d756)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1250)
=> Remove flow-osgi from vaadin-bom (#1249) in V15

versions.json
CustomFieldFlow was bumped to 4.1.0, but that version is for Flow 3.1 and lacks the `@HtmlImport` annotation.
Fixes https://github.com/vaadin/vaadin-custom-field-flow/issues/75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1446)
=> Downgrade CustomFieldFlow to 3.1.0 in V14.3

versions.json
CustomFieldFlow was bumped to 4.1.0, but that version is for Flow 3.1 and lacks the `@HtmlImport` annotation.
Fixes vaadin/vaadin-custom-field-flow#75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1455)
=> Downgrade CustomFieldFlow to 3.1.0 in V14.3 (#1446)

BUILD.md, scripts/generateBoms.sh, scripts/generator/src/creator.js, versions.json
The idea behind this refactoring is to change the order in CI builds:
- first the version is set in `pom.xml` file by running `mvn versions:set -DnewVersion=n.n.n`
- second poms are generated with the version specified above by running `./scripts/generateBoms.sh`
No need to maintain version numbers of platform and flow components in versions.json, as well as in generator script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/platform/1629)
=> re-factor: refactor bom generator

versions.json
15.0.0.rc1 is basically the same as the next 14.0 release, but version is bumped to help maintenance.
=> Bump Spring addon for v18

scripts/generator/templates/template-release-notes.md
Currently it does not render link properly:
```
[18.0.1)}(https://github.com/vaadin/vaadin-flow-components/releases/tag/18.0.1)
```
=> Fix components release notes markdown [skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml
Add fusion-endpoint dependency to endpoint testing modules.
https://github.com/vaadin/flow/pull/9499 needs to be merged first.
=> chore: add fusion-endpoint to vaadin-core

vaadin-platform-test/pom.xml
older version uses outdated sauce-connect which cause validation fail
=> Update ci-sauce version

.gitignore, platform-servlet-containers-tests/bnd-tools-test/pom.xml, vaadin-platform-test/pom.xml, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
By attaching two groups with distinct users, and asserting
that two avatars are visible, it ensures that Collaboration
Engine is working and synchronizing the avatars.
=> Add smoke test for CollaborationAvatarGroup

pom.xml
some old dependencies are not existing in the new snapshot repo, for example, vaadin-testbench-bom, so add the old one back
=> chore:add old snapshot repo

README.md
- removed archived Flow components repositories
- added links to WC and Flow monorepos
- removed obsolete Expense Manager starter
=> chore: cleanup README for Vaadin 20

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, versions.json
The dev server and live reload functionality has recently been
factored out of flow-server (so that it can be excluded in 
production mode). Add the dependency to the new module
(vaadin-dev-server) to vaadin-core to not break existing projects.
=> chore: add vaadin-dev-server dependency

pom.xml
Changes in https://github.com/vaadin/platform/pull/2181 for limiting java version do not work
=> chore: java-17 is still unsupported in gradle

vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, versions.json
Disable PUSH in CE in order to avoid client side Push errors that breaks `ChromeComponentsIT.openPageNoClientSideError` test checking for client-side errors, and OSGi tests in `platform-servlet-containers-tests/bnd-tools-test`.
https://github.com/vaadin/collaboration-engine-internal/issues/615
This code will not compile until CE releases `3.2.0.alpha2` and platform depends on it
=> test: set openPageNoClientSideError to false, to avoid Push errors in client

pom.xml
move Jandex module to a profile.
when run `mvn test` or any lifecycle before `package` for platform, the build failed as Jandex module expects jar files from other modules which should be generated during package phrase.
this should fix the failure with the JDK test.
=> Chore: move Jandex module to a separate profile

scripts/generateBoms.sh
In docker containers, maven sometimes outputs an extra error which pollutes generated poms.
```
[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
21.0-SNAPSHOT
```
=> chore: ignore warning lines when running in a docker container [skip ci]

README.md
`vaadin-` part was removed from the repo names, removing it to avoid redirections
=> chore: remove extra prefix 'vaadin' in components repo URLs [skip ci]

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
The dependency removed in https://github.com/vaadin/platform/pull/2247 is still needed for OSGI
=> chore: revert removing bytebuddy dependency

scripts/generator/templates/template-release-notes-maintenance.md
start.vaadin.com (not vaadin.com/start) is the preferred way to start a new Vaadin app.
=> Fix: Point to start.vaadin.com

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
when `grid.browsers` is not set from command line, use the setting from code file.
=> test: forward grid.browsers parameter (14.x)

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
after flow updated the jsoup version (https://github.com/vaadin/flow/commit/688ee59c54f79f4ec906b5b54ce20b662c155747), we need the following changes to make the OSGi test pass.
=> chore: add jsoup dependency

vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml, vaadin-platform-servlet-containers-tests/pom.xml
fix the osgi test
add `flow-server` to the module to get all the transitive dependencies.
=> chore:fix osgi test

vaadin-platform-hybrid-test/pom.xml, vaadin-platform-test/pom.xml
the LATEST version of Web Driver Manager requires higher version of JDK (instead of JDK8)
=> chore: use fixed webdriver manager

versions.json
This reverts commit dbb6a4f48c8d111cb8c580698085193b355ce5b7.
Recent fix in Chart web component has brought in a [regression](https://vaadin.slack.com/archives/C3TGRP4HY/p1632242505221100?thread_ts=1631875262.193500&cid=C3TGRP4HY)
=> Revert "chore: update versions.json in 14.8 with latest WC (#2402)"

versions.json
This reverts commit edc303d16a729d84b2a0caae35b41cdd03af626f.
Recent fix in Chart web component has brought in a [regression](https://vaadin.slack.com/archives/C3TGRP4HY/p1632242505221100?thread_ts=1631875262.193500&cid=C3TGRP4HY)
=> Revert "chore: update versions.json in 14.7 with latest WC (#2401)"

scripts/generator/templates/template-release-notes-maintenance.md
update the version used for release note. 
as vaadin prefix is still needed for V21 and V20
=> chore: correct the releasenote template [skip ci]

scripts/generator/templates/template-release-notes.md
In Vaadin 22 we use some APIs like [gap property for Flexbox](https://caniuse.com/flexbox-gap) that require Safari 14.1 / iOS 14.5+
- Release notes update
=> chore: update Safari and iOS versions for V22

versions.json
Bump `vaadin-text-field` to `2.9.0`
=> chore: update versions.json in 14.8 for new minor of vaadin-text-field

vaadin-platform-test/bnd.bnd
fix master branch snapshot failure with OSGi
=> chore: add back the missing bnd file

vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java
License names used by some projects that define their license to be something like to http://projectdomain.com/license, for which the contents might change without notice
for example: the vaadin__vaadin-mobile-drag-drop::1.0.1
this workaround has been used in flow project https://github.com/vaadin/flow/blob/9c232b8a0d58c29ac76cf9f04f520033c0dbfa6e/build-tools/src/test/java/com/vaadin/LicenseCheckTest.java#L62
checking the generated license.xml after `maven license:download-licenses`
with 1.0.0 version 
```
<dependency>
<groupId>org.webjars.npm</groupId>
<artifactId>vaadin__vaadin-mobile-drag-drop</artifactId>
<version>1.0.0</version>
<licenses>
<license>
<name>Apache-2.0</name>
<url>https://spdx.org/licenses/Apache-2.0#licenseText</url>
<distribution>repo</distribution>
<file>apache-2.0 - …
```
=> chore: add workaround for dependency license

versions.json
match the version with flow 10.0-SNPSHOT
=> chore: update spring addon to 20.0-SNAPSHOT

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
remove the duplicated `security vulnerability`
feature request template content has been used in [flow-components](https://github.com/vaadin/flow-components/issues/new?assignees=&labels=i%3A+needs+triage&template=feature_request.md&title=)
=> chore: add feature request template [skip ci]

scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
- remove upgrade guide from release note template of prerelease
- mention Java 11 minimal support in prerelease and final release note template
=> chore:update releasenote [skip ci]

vaadin-platform-test/bnd.bnd
bnd plugin 3.5.0 does not recognize JavaSE-11 as a valid version so it writes "UNKNOWN" by default
bnd plugin 6.0.0 writes the correct Java version but adds lots of import packages which should not be there
=> fix: Write correct manifest for test module

hilla-spring-boot-starter/pom.xml, hilla/pom.xml, pom.xml, scripts/generator/templates/template-hilla-bom.xml
as hilla bom will be released from version 1.0. extracting `hilla.version` as a property, so that we can set a version before doing a release
=> chore: refactor hilla artifacts

vaadin-platform-javadoc/pom.xml
when generating javadoc by using java 11, those dependencies are needed.
we don't have javadoc generation during PR validation, so i skipped ci for this PR
=> chore: provided dependencies for javadoc generation under java 11 [skip ci]

vaadin-core/pom.xml
`fusion-endpoint` will be part of Hilla, not Vaadin.
- As a Vaadin Flow user without Endpoints, this change shouldn't affect anything. 
- As a Hilla/Fusion user, it's recommended to change the dependency from `vaadin` to `hilla`, where the Endpoint is included.
- As a hybrid user, could update the pom file to include both `vaadin` and `hilla` dependencies.
=> feat!: remove fusion-endpoint from vaadin

versions.json
Updated to the version that has correct `"postinstall"` script.
=> chore: update vaadin-usage-statistics to 2.1.2

scripts/generator/templates/template-vaadin-bom.xml
Some libraries like testcontainers (there are others) define a dependency to an older jna version. 
As the jna dependency of the license checker comes from e.g. collab-engine -> license-checker -> oshi-core -> jna it is often overridden by another version.
Having it in the bom guarantees that you get a new enough version that e.g. works on new macs.
=> chore: Define jna version

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/resources/vaadin-featureflags.properties
When the component goes to production we should add these tests back without the properties file
=> test: remove vaadin-map smoke tests while it is experimental

vaadin-platform-gradle-test/build.gradle
This asures that in CI tests use the actual compiled and installed platform version
=> chore: use local repo just before prereleases one

versions.json
Starting from [23.0.0-alpha3](https://github.com/vaadin/web-components/releases/tag/v23.0.0-alpha3), web components use internal logic instead of the legacy `iron-a11y-announcer` dependency.
- Dependency update
=> chore: remove no longer used iron-a11y-announcer

vaadin-core-jandex/pom.xml, vaadin-jandex/pom.xml
Presence of fusion-endpoint classes in index may break quarkus builds because of Spring API usage.
Refs vaadin/quarkus#65
=> chore: remove fusion-endpoint from jandex index

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-vaadin-spring-bom.xml, versions.json
since Vaadin 23, spring addon has been moved to flow project, so let us remove the separate entry for spring.
=> chore: remove flow-spring entry from version.json

vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java
those licenses are coming from [this patch](https://github.com/vaadin/quarkus/commit/94693a14eb76e28fca82fb6d99516ee172630131), transitive dependency from the quarkus-websockets
=> chore: add license to whitelist

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
- the first row will be used as title for the relelase
- the note is needed, as we got feedback that user get confused with spring and hilla version and name
=> chore: update relelase note for v23.1 [skip ci]

scripts/generator/templates/template-vaadin-bom.xml, versions.json
Update license checker version to 1.4.1
Aligns jna version with license-checker transitive dependencies
Align slf4j version with flow mater 23.1
=> chore: Update license checker and jna version

versions.json
In Vaadin web components 23.1 we added a new package as part of https://github.com/vaadin/web-components/issues/266
Adding it here so its version gets locked, even though it does not depend on any components.
=> chore: add lit-renderer package to versions.json

hilla/pom.xml
after https://github.com/vaadin/flow/pull/14014 changes, flow is checking the hardcoded vaadin-versions.json in the jar. 
hilla should be updated accordingly. 
fixes #3089
=> chore:pack the correct versions.json after previous update

vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java
Prevents the following failure:
licenses that have not been whitelisted: 
dependency 'com.auth0:java-jwt' has licenses : [The MIT License (MIT): https://raw.githubusercontent.com/auth0/java-jwt/master/LICENSE]
=> Add different URL for MIT license coming from java-jwt

versions.json
starting from this version, CE doesnt have the npmPackage annotation for field-highlighter.
=> chore: update CE to 5.0.3

versions.json
1.2.1+ has some bugfixes regarding headless mode
1.4+ has offline related changes so let's not go there yet
=> chore: Upgrade license checker

vaadin-platform-javadoc/pom.xml
the `javax.servlet-api` dependency is removed from flow, but CE and other modules (potentially) are still using it. 
provide this dependency here for javadoc generation
=> chore: provide dependency for javadoc generation

pom.xml
=> chore: update vaadin-parent to 2.1.0

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts
The default slot in `vaadin-checkbox` and `vaadin-radio-button` is deprecated and might be removed in V24.
Updated the ITs to use `label` property instead, to align with other components e.g. `vaadin-text-field`.
- Tests
=> test: do not use deprecated default slot

vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java, versions.json
Update vaadin-quarkus to 2.0.0.alpha2 for Vaadin 24
=> chore: update vaadin-quarkus to 2.0.0.alpha2 for Vaadin 24

vaadin-platform-gradle-test/build.gradle
currently gradle portal has failed, 3.0.4 doesn't have artifacts in maven, let us try with the newer version which is available at both nexus
=> chore: update gretty version

versions.json
=> chore: Upgrade license checker to 1.11.2

vaadin-core/pom.xml
This is now Prime+ and must be manually added as a dependency when you use it
=> chore: Remove flow-polymer-template from vaadin-core

scripts/generator/src/creator.js, scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-bom.xml, versions.json
you can test with running 
`./scripts/generateBoms.sh` at the root of platform
then check the generated `pom.xml` under `vaadin-bom` folder
=> chore: add kits to vaadin-bom and releasenote (23.3) [skip ci]

scripts/generator/templates/template-release-notes.md, versions.json
duplicated entry for collaboration-engine
chain validation will land in V24
=> chore: fixes before final 23.3 [skip ci]

.github/workflows/pit.yml
* update PIT.yml to get rid of warnings
* get rid of the set-output usage
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore: update PIT.yml to get rid of warnings (#3432) (CP: 23.3) [skip ci]

.github/workflows/sbom.yml, vaadin-testbench/pom.xml, versions.json
Pinned dependencies should be reverted when
- CE releases a new alpha
- [async-http-client](https://github.com/AsyncHttpClient/async-http-client) releases [3.0.0](https://github.com/AsyncHttpClient/async-http-client/issues/1846) and selenium releases a version with that
=> chore: temporary fix TB vulnerabilities in platform

scripts/generator/templates/template-dev-bundle-pom.xml
The feature flags file should not be included in the dev-bundle jar
as it then controls the application build if the application doesn't contain
it's own feature flags file.
=> fix: do not add the feature flags file to dev-bundle jar

.github/workflows/sbom.yml
This fixes error in builds that happens when pushing to main branches like [here](https://github.com/vaadin/platform/actions/runs/3993924506/jobs/6851077977)
=> chore: fix comment-pull-request when event is something else

vaadin-platform-hybrid-test/pom.xml, vaadin-platform-test/pom.xml
the productionMode parameter has not been needed since https://github.com/vaadin/flow/pull/15390
=> chore: Simplify production mode specification

versions.json
updated the vulnerable jackson-databinding
=> chore: update CE to 5.2.1

vaadin-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java
This is needed to include sw.js to the default bundle, so making a new bundle isn't needed if PWA is used in the app.
Depends on https://github.com/vaadin/flow/pull/15989
Related-to https://github.com/vaadin/flow/issues/15970
=> fix: Add PWA to the default bundle

vaadin/pom.xml, versions.json
This should allow exclusion of vaadin-dev from the production bundle
=> fix: Make vaadin depend on vaadin-core instead of vaadin-dev (CP:24.0)

.github/workflows/pit.yml
Fixes: https://github.com/vaadin/flow/issues/16097 
Related to: regression described at https://maven.apache.org/docs/3.8.4/release-notes.html
=> fix: maven 3.8.2 and 3.8.3 are broken [skip ci]

vaadin/pom.xml
This should allow exclusion of vaadin-dev from the production bundle
=> fix: Make vaadin depend on vaadin-core instead of vaadin-dev

vaadin-dev-bundle/frontend/themes/vaadin-dev-bundle/theme.json
Because it was only added for start.vaadin.com that doesn't use it anymore.
=> chore: Exclude line-awesome from default dev-bundle

scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
this fixes the javadoc generation in snapshot build https://bender.vaadin.com/buildConfiguration/VaadinPlatform_TestReleasePlatformSnapshotToMavenVaadinPrerelease/384063?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true
=> chore: use spring-boot-bom for dependencies [skip ci]

versions.json
update to GA versions of CDI, Quarkus and MPR add-ons
update classic component to 24.0.0
=> chore: Upgrade modules for Vaadin 24.0.0

scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
the scope of these dependencies have been changed on flow side, https://github.com/vaadin/flow/commit/609e66a9563ceae5e16ecd0711c2e049ab4b7b68
=> chore: provide the dependencies for javadoc generation [skip ci]

scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
this dependency is coming from `flow-server` module which has been updated by this commit https://github.com/vaadin/flow/pull/16223
=> fixes: provided jakarta-annotation-api dependency for javadoc [skip ci]

pom.xml, scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
the spring dependency version will come from the `spring-boot-dependencies` bom.
=> chore: remove unnecessary spring versions [skip ci]

versions.json
This reverts commit bd7c97547aa24441e052aaff184ffd83918620af.
as flow didn't take this change yet ...
=> Revert "chore: Upgrade license checker to 1.12.3 (#3967) (#3969)" [skip ci]

vaadin-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java
Reverts vaadin/platform#3990
This update will cause us problems with the default bundle. We need to figure out the proper approach for 24.1 instead
=> Revert "chore: Upgrade vcf-nav to 1.1.1 (#3989) (CP: 24.0)"

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java, versions.json
This reverts commit 9689a59c824214d24fd19a3e525adfcd78ace695.
fixes #3867
=> Revert "chore: temporally disable safari test (#3868)"

versions.json
this version has not been included in Flow release. merge PR after https://github.com/vaadin/flow/pull/16392 and Vaadin 24.0.2 release
=> update license-checker to 1.12.3  [skip ci]

scripts/generateAndCheckSBOM.js
We will keep using spring 5 in Vaadin 23. so we cannot really update here. 
the same CVE has been added to the whitelist and now it is just an updated version of spring.
=> chore: add spring-web to known cve list

.gitignore, pom.xml, scripts/generateBoms.sh, scripts/generator/generate.js, scripts/generator/templates/template-prod-bundle-pom.xml, scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core/pom.xml, vaadin-prod-bundle/frontend/themes/vaadin-prod-bundle/theme.json, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java
This adds a standalone maven module for default prod bundle. The bundle is generated in a regular way with 'build-frontend' goal. Will be used by Flow in case if an app has no frontend add-ons.
Part-of https://github.com/vaadin/platform/issues/4046
=> feat: Add default production bundle module

.github/workflows/sbom.yml
this allows to force push the sbom artifacts to releasenote even when there are founded vulnerabilities.
=> chore: force push sbom artifacts for release [skip ci]

hilla-react-spring-boot-starter/pom.xml, pom.xml, scripts/generator/templates/template-hilla-bom.xml
Closes #4027.
If this PR is OK, then the direct dependency from `dev.hilla:hilla` or `dev.hilla:hilla-react` could be removed in Start projects.
=> feat: add `hilla-react-spring-boot-starter` module

scripts/generateAndCheckSBOM.js, vaadin-quarkus-extension/pom.xml
The 'vaadin-quarkus' artifact, defined in 'vaadin-quarkus-extension', has a compile scoped dependency to 'flow-server', whose version is fixed during the Vaadin Quarkus add-on release.
When resolving transitive dependencies, Maven picks the 'nearest definition', so in an application project, the 'flow-version' pinned in 'vaadin-quarkus' takes precedence over the one defined by the platform ('vaadin-core'). To get the correct version the application project needs to also import the Vaadin BOM.
Adding the exclusion of 'flow-server' in 'vaadin-quarkus' allows to use 'vaadin-quarkus-extension' in an application project without importing the platform BOM.
=> chore: adjust transitive flow-server dependency in quarkus extension

vaadin-quarkus-extension/pom.xml
The vaadin-quarkus extension artifact is not enough to create a new Vaadin based Quarkus application, as it only depends on flow-server, and it misses jandex index and Vaadin components.
To better integrate with Quarkus tooling, this artifact should be registered within the Quarkus egistry, but it has to contain the Quarkus metadata file that is present in the vaadin-quarkus artifact.
=> chore: add metadata to vaadin-quarkus-extension

vaadin-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java
Having external dependencies without a managed the version makes it impossible to upgrade those dependencies. We already remove used of line-awesome as an npm dependency in 24.0 and vcf-nav is being replaced in 24.1 with `vaadin-side-nav`
=> chore!: Remove external modules from dev and prod bundle

versions.json
bump MPR to `5.1.0.alpha1` in `versions.json` for the 22.1 branch.
Relevant release notes:
- https://github.com/vaadin/multiplatform-runtime-internal/releases/tag/5.1.0.alpha1
=> chore: bump MPR to 5.1.0.alpha1

vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/IconView.java
Reduces the size of the intial bundle from 1.3MB to 1.0MB (uncompressed)
=> fix: Change vaadin iconset to be lazy loaded

scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml, scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
If a project doesn't have a lock file and vaadin-dev is excluded from the dependencies, Flow regenerates the lock file, which takes time. This patch add dev bundle to the Vaadin plugin, so Flow can find it and copy lock file from there.
Fixes https://github.com/vaadin/flow/issues/16041
=> chore: Add dev bundle to vaadin-maven-plugin

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
safari 15 and firefox esr have been listed in the note as supported browsers.
saucelabs is using safari 15.1 as testing browser. but the feature, `csslayerblockrule`,  we depends on is from safari 15.4
=> chore: Add supported browsers to tests

.github/workflows/sbom.yml
starting from 2.6.1, the plugin checks the body variable for overwriting the release note content. 
let us remove them as it is not necessary. 
tested with platform 23.3.13 release.
=> chore: remove the unnecessary body content with asset upload [skip ci]

hilla-dev/pom.xml, hilla-react-spring-boot-starter/pom.xml, hilla-react/pom.xml, hilla-spring-boot-starter/pom.xml, hilla/pom.xml, pom.xml, scripts/generator/templates/template-hilla-bom.xml, scripts/generator/templates/template-servlet-containers-tests-pom.xml, vaadin-platform-hybrid-test/pom.xml, vaadin-platform-test/pom.xml
this will simplify the hilla release build by calling the `hilla` profile instead of using `-pl`
=> chore: group platform modules in a profile, remove gradle module activation rule

pom.xml
this will resolve the CVE reported on `spring-boot-web` dependency which depends on `tomcat-embed-core` https://nvd.nist.gov/vuln/detail/CVE-2023-34981
=> chore: upgrade sb to 3.1.1

pom.xml, scripts/generateAndCheckSBOM.js, versions.json
this will resolve the CVE reported on spring-boot-web dependency which depends on tomcat-embed-core https://nvd.nist.gov/vuln/detail/CVE-2023-34981
=> chore: update flow to 24.0.11 and spring.boot to 3.0.8 (24.0)

scripts/generateAndCheckSBOM.js, vaadin-platform-sbom/pom.xml, versions.json
* chore: update swing-kit 2.1.0
=> chore: update swing-kit 2.1.0 (#4351)

vaadin-platform-hybrid-test/frontend/views/components/components-view.ts
this class has been removed in the latest side-nav release
=> chore: remove not needed imports

scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
new dependency has been added on flow side https://github.com/vaadin/flow/commit/349cc1105a1e5901863ddd210120ff3606490e47#diff-634e85ae9a7dd3ca2d705273509f0a294cbd424c616316f8b78aa7b6eb7eba41
currently platform javadoc generation step has failed.
=> chore: provide spring-boot-devtool to javadoc generation [skip ci]

vaadin-spring-boot-starter/pom.xml
in spring-boot 3.1.4, the integrated version of tomcat-core is 10.1.13, so that the version overwrite is not necessary any more
=> remove outdated tomcat exclusions

scripts/generateAndCheckSBOM.js
as dependency-check plugin has been upgraded, this exclusion is not needed any more.
=> Remove not needed CVE exclusions [skip ci]

scripts/generator/templates/template-dev-bundle-pom.xml, vaadin-dev-bundle/src/test/java/com/vaadin/devbundle/BundleTest.java, vaadin-platform-test/pom-dev.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java, versions.json
The package feature for devBundle
moves the dev bundle files to a
new folder. Copy from new folder
when generating jar.
Depends on vaadin/flow#17977
=> fix: copy dev bundle files from correct place

scripts/generateAndCheckSBOM.js, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java, versions.json
Imports `dndConnector.js` to the prod bundle, as now there is nothing that triggers this import - DragSource and DragTarget were removed from Grid, see https://github.com/vaadin/flow-components/pull/5686.
=> fix: Add DnD Connector to prod bundle

scripts/generator/templates/template-dev-bundle-pom.xml, scripts/generator/templates/template-prod-bundle-pom.xml, vaadin-gradle-plugin/build.gradle
this PR fix the issue with gradle release. 
add `mavenLocal()` repository to **build.gradle** , which let the plugin module to find the dev-bundle/prod-bundle with new versions. 
maven has it own reactor for build modules, which defines the order of all modules. `vaadin-bom` is coming after bundle modules. so it fails the build with cannot find bom modules in the build log.
=> chore:fix gradle release issue

vaadin-gradle-plugin/build.gradle, vaadin-gradle-plugin/gradle/wrapper/gradle-wrapper.properties, vaadin-gradle-plugin/gradlew, vaadin-platform-gradle-test/build.gradle, vaadin-platform-gradle-test/gradle/wrapper/gradle-wrapper.properties
this let the project work with calling `mvn install`
which has been reported in #4668 .. 
currently gradle 8.4 is not supporting JDK 21 fully.. so let us check again after.
=> chore: update gradle and kotlin versions 

versions.json
Related to https://github.com/vaadin/flow/issues/18149
We missed to add `@vaadin/overlay` to `versions.json` for Vaadin 23, which prevents PNPM from locking it properly.
- Bugfix
=> fix: add missing vaadin-overlay npm package version (23.3)

vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
in TB 9.2.0, the wait for spinner has been integrated in the `waitForVaadin()` method.
=> chore: remove extra wait for dev spinner

scripts/generateAndCheckSBOM.js
this license has been added to 24.3 and main branch
=> chore: add blueOak license to whitelist [skip ci]

vaadin-spring-boot-starter/pom.xml
the new version has been used in spring-boot 3.2.1
=> chore: remove unnecessary logback dependency overwrite [skip ci]

vaadin-spring-boot-starter/pom.xml
User needs to exclude hilla-react and add hilla if they want to use hilla-lit instead of hilla-react
=> chore: vaadin-spring-boot-starter should bring the hilla-react by default instead of hilla

scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml
This fix the problem with relativity of where the `mvn` command is executed regarding the groovy script in `vaadin-gradle-plugin`'s template pom file.
=> feat: make groovy script agnostic to where maven runs

scripts/generateAndCheckSBOM.js, scripts/generator/generate.js, scripts/generator/templates/template-dev-bundle-pom.xml, scripts/generator/templates/template-prod-bundle-pom.xml, vaadin-dev/pom.xml, vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java, vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java, vaadin-spring-boot-starter/pom.xml, versions.json
Fixes: #4946
Note! Need to merge first Hilla's https://github.com/vaadin/hilla/pull/2001.
=> chore: add hilla-dev-mode in vaadin-dev

scripts/generator/templates/template-dev-bundle-pom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-dev-bundle/src/test/java/com/vaadin/devbundle/BundleTest.java, vaadin-dev/pom.xml, vaadin-platform-sbom/pom.xml, versions.json
We will no longer update Copilot for 24.3 so we will remove it to avoid later compatibility problems
=> chore: Remove Copilot from 24.3

vaadin-spring-boot-starter/pom.xml
Since `hilla` and `hilla-react` have the same content after recent changes, keeping both is redundant.
If we would like to remove one of them, it would make sense to keep only `hilla`, the one with a shorter and simpler name.
=> refactor: replace hilla-react with hilla

pom.xml, scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
this `<includeTransitiveDependencySources>` has been deprecated in maven-javadoc-plugin.
=> remove deprecated configuration [skip ci]

.github/workflows/pit.yml, .github/workflows/sbom.yml
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3, actions/setup-java@v3, stCarolas/setup-maven@v4.5, actions/upload-artifact@v3.1.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> chore: get rid of GHA warning of using Node 16 [skip ci]

pom.xml, scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
related with: https://github.com/vaadin/hilla/issues/2091
=> chore: exclude hilla-parse and hilla-runtime package for javadoc [skip ci]

versions.json
Adds "mode": "lit" to core and pro web-components. Flow will need this information to update package.json dynamically. All dependencies in lit mode are already included in react-components dependency.
Related-to: vaadin/flow#18684
=> chore: add mode property to versions.json

versions.json
These mixins, when excluded, are installed into `node_modules`, but the overall theming is broken and the lumo styles are not applied to UI:
=> fix: Remove non-components deps from exclusion list

vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java
These tests were temporary disabled during the unification of hilla in platform, and needs to be re-enabled before beta1
=> test: re-enable tests checking usage of bundle

vaadin-quarkus-extension/pom.xml
Hilla dependency imports Spring that may not be wanted for a Quarkus based Vaadin application.
In addition, Hilla will currently not work on Quarkus because it uses Spring feature that are not supported by Quarkus extensions for Spring.
=> fix: exclude Hilla from Vaadin Quarkus extension [skip ci]

versions.json
It will have a deployed version when we have the first alpha for 24.5
=> chore: align hilla and flow versions with main 24.5-SNAPSHOT

versions.json
Platform SBOM switched from CycloneDX spec version 1.4 to 1.5 and this happened automatically (it probably uses the latest) while AppSec Kit 3.1 has version 1.4 managed by its POM. This might cause an exception when using kit with 24.4.
AppSec Kit 3.2 now uses the latest CycloneDX spec version 1.5.
=> chore: update appsec-kit-starter to 3.2.0.beta1

scripts/generator/src/creator.js
we dont generate that content with the releasenote template nowadays.
fix #6509
=> chore: drop changeSince function [skip ci]

scripts/generateAndCheckSBOM.js
disable bomber temporarily, as there is a failure with error 
```
!! ERROR 1 !! running: bomber scan target/bom-vaadin.json --output json!!
■ json: cannot unmarshal number into Go struct field Severity.vulns.severity.type of type string
```
seems people are reporting this issue as in https://github.com/google/osv.dev/issues/2335
=> chore: disable bomber temporarily [skip ci]

scripts/generator/templates/template-release-notes-prerelease.md
as we dont have release note for copilot prerelease version in the public repo
=> use docs link for prerelease version [skip ci]

versions.json
I missed to include this change when adding Popover in #6637. This fixes wrong auto-import when using React.
- Bugfix
=> fix: add popover package to React components exclusions

vaadin-core-jandex/pom.xml, vaadin-core-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java, vaadin-jandex/pom.xml, vaadin-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java
This change makes jandex artifact dependencies provided scoped, to prevent to import transitive dependencies in the user project. It also excludes from the index potentially optional dependencies such as vaadin-dev-server (usually excluded from production builds) and flow-react (user can opt-out as documented online)
Part of vaadin/quarkus#158
=> chore: prevent jandex artifacts to import transitive dependencies

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md, scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml, scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-dev/pom.xml, versions.json
The dependency is commercial so it cannot be a dependency of `vaadin-dev`. We cannot move it to be a dependency of `vaadin` either as it then will end up in the production artifacts.
Additionally it seems this is a dependency that should not be used in end user projects, at least not right now, so having it outside the platform is fine.
Fixes #6915
=> chore: Remove ui-tests dependency

pom.xml
this was used when flow was released with spring prerelease versions
=> chore: remove spring repo [skip ci]

vaadin-dev/pom.xml, versions.json
- `dependency convergence` : there two different versions of io.netty:netty-* in this reactor-netty:1.2.0 , which are 4.1.114 and 4.1.113
- `vulnerable dependency` : the reactor-netty:1.2.0 uses io.netty:netty-common:4.1.114 which contains https://github.com/netty/netty/security/advisories/GHSA-xq3w-v528-46rv
=> fix: dependency convergence error from copilot

vaadin-dev/pom.xml, versions.json
- `dependency convergence` : there two different versions of io.netty:netty-* in this reactor-netty:1.2.0 , which are 4.1.114 and 4.1.113
- `vulnerable dependency` : the reactor-netty:1.2.0 uses io.netty:netty-common:4.1.114 which contains https://github.com/netty/netty/security/advisories/GHSA-xq3w-v528-46rv
=> fix: dependency convergence error from copilot (#6998)

.github/workflows/pit.yml, vaadin-platform-react-hybrid-test/src/main/frontend/views/flow/no-layout.tsx, vaadin-platform-react-hybrid-test/src/main/frontend/views/home/deep/hello.tsx, vaadin-platform-react-hybrid-test/src/main/java/com/vaadin/platform/react/test/views/DeepLayout.java, vaadin-platform-react-hybrid-test/src/main/java/com/vaadin/platform/react/test/views/FlowLayout.java, vaadin-platform-react-hybrid-test/src/test/java/com/vaadin/platform/react/test/FlowMainLayoutIT.java
Add tests for testing use of
flowLayout as both true and false
in same layout path.
Add test for hilla view with a deep
path that should get a Flow layout.
=> feat: Add test for mixed flowLayout and deep tree

.github/workflows/sbom.yml, versions.json
```
TypeError: licenseWhiteList.toSpliced is not a function
```
Array.prototype.toSpliced() is relatively new feature of node.js, not part of the ECMAScript standard. Even Chrome has these methods available only since version 110 and node only since version 20.0.0
=> chore: use node latest version [skip ci]

vaadin/pom.xml
=> chore: remove profile activation

scripts/generator/templates/template-release-notes-maintenance.md, scripts/generator/templates/template-release-notes-prerelease.md, scripts/generator/templates/template-release-notes.md
Changed based on feedbacks:
- Remove mentions of Designer (and I assume Design System Publisher too, since we’re not actively promoting it?).
- Remove mentions of Classic Components (as these are deprecated).
- Add a mention of the Modernization Toolkit update, including: Feature Pack, Dragonfly, Modernization Toolkit Analyzer
=> chore: update release note templat [skip ci]

scripts/generateAndCheckSBOM.js, vaadin-platform-sbom/pom.xml
issue https://github.com/netplex/json-smart-v2/issues/240
```
No versions available for net.minidev:json-smart:jar:[1.3.3,2.4.10] within specified range 
```
=> chore: add a workaround to resolve the no version in the range [skip ci]

.github/workflows/pit.yml
This fixes the '[: too many arguments' error when running pit preparation script
https://github.com/vaadin/platform/actions/runs/13815919957/job/38651445513#step:2:31
=> chore: fix error in workflow actions when assigning CE_LICENSE string in bash [skip ci]

scripts/generator/templates/template-vaadin-spring-bom.xml, vaadin-core-components/pom.xml, vaadin-dev-bundle/src/main/resources/vaadin-featureflags.properties, vaadin-platform-hybrid-test/frontend/views/components/components-view.ts, vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java, vaadin-platform-test/src/main/resources/vaadin-featureflags.properties, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java, vaadin-prod-bundle/src/main/resources/vaadin-featureflags.properties, vaadin-testbench-junit5/pom.xml, vaadin-testbench/pom.xml, versions.json
Adds the Card Flow component as preview feature to 24.7.
Depends on https://github.com/vaadin/flow-components/pull/7275 to be released first, as compilation for `card.setTitle` will fail otherwise.
- Feature
=> feat: add Card Flow API preview to 24.7

.github/workflows/pit.yml
This reverts commit 63ec5aedb524566207e7b8098a947d774b3f7fad.
=> Revert "chore: downgrade helm version to avoid regression introduced in 3.18.0 (#7651)" [skip ci]

versions.json
Updates Collaboration Kit (`vaadin-collaboration-engine`) to version 6.5.0
=> Chore: Update Collaboration Kit to 6.5.0

vaadin-prod-bundle/frontend/themes/vaadin-prod-bundle/theme.json, vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java, vaadin-prod-bundle/src/test/java/com/vaadin/prodbundle/AllComponentsIncludedTest.java, versions.json
```
this theme in vaadin-prod-bundle was added to include Lumo into the default prod bundle. I agree we now can remove the @Theme(“vaadin-prod-bundle”) and corresponding theme folder.
```
=> chore: fix prod bundle test after the recent theme changes
